### ISSUE TITLE
"Train_Size = None error, resulting train set will be empty"

### ISSUE THREAD

**Issue by aaron387** [AliaksandrSiarohin/first-order-model#102]
**Here is what I get when I compile.** 

run.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Use random train-test split.
Traceback (most recent call last):
  File "run.py", line 72, in <module>
    dataset = FramesDataset(is_train=(opt.mode == 'train'), **config['dataset_params'])
  File "C:\Program Files\first-order-model-C\first-order-model\frames_dataset.py", line 83, in __init__
    train_videos, test_videos = train_test_split(self.videos, random_state=random_seed, test_size=0.5)
  File "c:\program files\python37\lib\site-packages\sklearn\model_selection\_split.py", line 2122, in train_test_split
    default_test_size=0.25)
  File "c:\program files\python37\lib\site-packages\sklearn\model_selection\_split.py", line 1805, in _validate_shuffle_split
    train_size)
**ValueError: With n_samples=1, test_size=0.5 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.**

_Not sure if I set up the pairing correctly. I pointed to the directory as shown below._ 

_pairs_list='C:\Program Files\first-order-model-C\first-order-model\data\bair256.csv',_

**The complete code:**

python run.py --config 'C:\Program Files\first-order-model-C\first-order-model\config\bair-256.yaml' --mode animate --checkpoint 'C:\Program Files\first-order-model-C\first-order-model\data_sets\vox-adv-cpk.pth.tar'

**Comment by AliaksandrSiarohin** [comment]
You should create train and test folder. data/bair/test and data/bair/train

**Comment by aaron387** [comment]
> You should create train and test folder. data/bair/test and data/bair/train

Thanks. Made those changes shortly after making this post. I'm getting a new error though relating to CUDA and the gpu id's. 

CUDA_VISIBLE_DEVICES=0 : The term 'CUDA_VISIBLE_DEVICES=0' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:2 char:1
+ CUDA_VISIBLE_DEVICES=0 python run.py --config 'C:\Program Files\first ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CUDA_VISIBLE_DEVICES=0:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Tried removing cuda and then I got an error relating to the i'ds.** 

Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "C:\Program Files\first-order-model-C\first-order-model\train.py", line 87, in train
    'optimizer_kp_detector': optimizer_kp_detector}, inp=x, out=generated)
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by AliaksandrSiarohin** [comment]
Size of your dataset is less than one batch.

**Comment by aaron387** [comment]
ah, that makes sense. Thank you.

**Comment by aaron387** [comment]
Yup good to go. Getting RAM error but I fixed it by lowering settings in the config. Probably should only use 256 as well haha. 512 is generally to large for training.
