### ISSUE TITLE
Is there a way to run this without NVIDIA gpu and cuda?

### ISSUE THREAD

**Issue by daggydove** [AliaksandrSiarohin/first-order-model#103]
Thought I'd give this a try after reading through and not seeing anything about it, but now I'm getting: "AssertionError: Torch not compiled with CUDA enabled" when running demo.py
Thanks, and sorry for my ignorance, I'm pretty new to this stuff.

**Comment by AliaksandrSiarohin** [comment]
use --cpu option

**Comment by daggydove** [comment]
Thanks!

**Comment by daggydove** [comment]
is there a similar option for crop-video.py?

**Comment by AliaksandrSiarohin** [comment]
No. Change
```
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
```
To
```  
  fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False, device='cpu' )

```

**Comment by daggydove** [comment]
Thanks!
