### ISSUE TITLE
Not able to use !gdown

### ISSUE THREAD

**Issue by abhinavsp0730** [AliaksandrSiarohin/first-order-model#108]
!gdown  https://drive.google.com/uc?id=1ML-Rpeaftox3z7b1GThUZtl1Ql_lGUrb
doing this but I'm getting :
ermission denied: https://drive.google.com/uc?id=1ML-Rpeaftox3z7b1GThUZtl1Ql_lGUrb
Maybe you need to change permission over 'Anyone with the link'?

**Comment by AliaksandrSiarohin** [comment]
No folder have proper permissions, anyone with link can view.
