### ISSUE TITLE
Bilinear warping behavior explanation

### ISSUE THREAD

**Issue by Daiver** [AliaksandrSiarohin/first-order-model#110]
Hi! Thank you for great paper!

In `README.md` i found following text
> Note: It is important to use pytorch==1.0.0 for training. Higher versions of pytorch have strange bilinear warping behavior, because of it model diverge.

Can you explain what exactly wrong with implementation of warping in higher pytorch versions?

Thank you in advance!

**Comment by AliaksandrSiarohin** [comment]
This is just a hypothesis because without it everything works as expected. During training the model diverge at some point and produce weird results, see https://github.com/AliaksandrSiarohin/first-order-model/issues/13

**Comment by Daiver** [comment]
Thank you for answer!
