### ISSUE TITLE
How do I crop vertical videos?

### ISSUE THREAD

**Issue by eSaniello** [AliaksandrSiarohin/first-order-model#111]
Hi,

You specified to crop all the videos to 256x256.
But what if I have a vertical video of 720x940?

The videos in the fashion dataset have such a resolution.
How do I crop those videos?
Should I crop only the width preserving the aspect ratio? Because otherwise I would not get the full person in the video.

Another question that I have is, How do I train on higher resolution images such as 512 or 1024? 
Should I make changes to the code for that?

Thanks

**Comment by AliaksandrSiarohin** [comment]
I just resize them to 256x256.
See related issue https://github.com/AliaksandrSiarohin/first-order-model/issues/81
