### ISSUE TITLE
ModuleNotFoundError: No module named 'demo'

### ISSUE THREAD

**Issue by Houssam47** [AliaksandrSiarohin/first-order-model#112]
Whenever i tried to create a model and loadcheckpoint .with launching this code in Google colab
from demo.py import load_checkpoints
generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
                            checkpoint_path='/content/gdrive/My Drive/first-order-motion-model/vox-cpk.pth.tar')
**I end up getting this ERROR**
from demo.py import load_checkpoints
generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
                            checkpoint_path='/content/gdrive/My Drive/first-order-motion-model/vox-cpk.pth.tar')

CAN SOMEONE HELP ME PLEASE THANK YOU

**Comment by AliaksandrSiarohin** [comment]
YOU DID NOT RUN, EITHER ```git clone ...``` or ```cd ...```.  OPEN NOTEBOOK AND RUN ALL THE CELLS ONE BY ONE.  THANK YOU.
