### ISSUE TITLE
No such file or directory: 'data/vox-png' <---> When Training for the first time (beginnner)

### ISSUE THREAD

**Issue by 1reverseengineer** [AliaksandrSiarohin/first-order-model#116]
Beginner here, when I try to train the neural network by pasting this code into the terminal (as requested in the README.md) 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python3 run.py --config config/vox-256.yaml --device_ids 0,1,2,3`

Error log: 
`FileNotFoundError: [Errno 2] No such file or directory: 'data/vox-png'`

In fact there is no vox.png file in the data folder. How can I correct this? My goal is to train the network on an image/get better results.

**OS:** Ubuntu 18.04.

**Comment by AliaksandrSiarohin** [comment]
You should download the dataset.

**Comment by 1reverseengineer** [comment]
Yea I figured it out a couple of days after that. I should've closed the issue sorry.

**Comment by puhuk** [comment]
Could you share how I set the directory path.
I downloaded Youtube-vox and preprocess with load_videos.py
