### ISSUE TITLE
Training discriminator without using it as loss for generator

### ISSUE THREAD

**Issue by arunmallya** [AliaksandrSiarohin/first-order-model#119]
In https://github.com/AliaksandrSiarohin/first-order-model/blob/master/config/vox-256.yaml#L61-L62, the setting is
```yaml
generator_gan: 0
discriminator_gan: 1
```
which means the discriminator is trained (https://github.com/AliaksandrSiarohin/first-order-model/blob/master/modules/model.py#L256), 
but not used as loss for training generator (https://github.com/AliaksandrSiarohin/first-order-model/blob/master/modules/model.py#L174-L193). 
Is this intentional? How is the discriminator used in this case?

Thanks!

**Comment by AliaksandrSiarohin** [comment]
It is not used.
