### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by AndroYD84** [AliaksandrSiarohin/first-order-model#12]
There's no license information for this repository, when no license is specified then it's implied that all rights are reserved and it is not Open Source or Free. No one can modify, redistribute or contribute to this code without explicit permission from the copyright holder. Lately in the deep learning community, innovative projects have been more and more restrictive with their licenses, I believe this have slowed down innovation and implementation of said solutions considerably as no one is willing to risk investing so much time into something that in the end cannot be freely used or is outrageously expensive, I'd really appreciate if you'd consider a license without any crippling restrictions as I'm sure there're lots of people who are itching to make something awesome with it (remember when GPT-2 best model was kept private, when they finally decided to released it, AI Dungeon 2 was born? That was mindblowing as no one ever thought of using it that way)

**Comment by shawwn** [comment]
I think this issue brings up some good points. Is there any update on this?

**Comment by AliaksandrSiarohin** [comment]
Creative Commons Attribution-NonCommercial 4.0 International
