### ISSUE TITLE
Weights are corrupted

### ISSUE THREAD

**Issue by gregoirerllr** [AliaksandrSiarohin/first-order-model#122]
Hi, I can't manage to extract the weight when it is downloaded. It seems the tar are corrupted.
The exact error message is: `tar: Error opening archive: Unrecognized archive format` after I do a `tar -xvf`
Thanks

**Comment by AliaksandrSiarohin** [comment]
It is not a tar. Use it as it is ```--checkpoint vox-cpk.pth.tar```
