### ISSUE TITLE
Questions about formula in Appendix A.3

### ISSUE THREAD

**Issue by DaddyJin** [AliaksandrSiarohin/first-order-model#125]
Thank you for your great work.
But i have a single question about the formula.
![Snipaste_2020-04-28_10-34-25](https://user-images.githubusercontent.com/22629481/80440670-db16c600-893b-11ea-852c-37451989c57d.png)
Here in the formula of the inference stage, we use taylor expansion to the first formula and let the zeroth order and the first order be equal correspondingly.
I am clear with the zeroth order.
But when it comes to the first order, which is the third formula in the image i paste, i think it should be J_1 = J_2 - J_3 + J_4, not J_1 = J_2 * J_3^-1 * J_4.
Could you give the details about the formula here?
Thank you in advance.
Best wishes.

**Comment by AliaksandrSiarohin** [comment]
So the jacobians can be thought as affine matrixes. When you want compute the composition of affine matrixes you multiply then. You can though for example about rotation matrixes A=[[cosx, sinx, - sinx, cosx]], B=[[cosy, siny, - siny, cosy]], multiplication will give AB = [[cosx+y, sinx+y, - sinx+y, cosx+y]], e.g rotation by angle x+y.

**Comment by DaddyJin** [comment]
Thank you. I get it!
Best wishes.
