### ISSUE TITLE
Questions about the pre-trained models of vox

### ISSUE THREAD

**Issue by Honlan** [AliaksandrSiarohin/first-order-model#127]
Hi~ First of all, thanks a lot for your awesome work, and may I ask two questions about the pre-trained models of vox?

1. what are the major differences between vox-cpk.pth.tar and vox-adv-cpk.pth.tar? I see some differences between vox-256.yaml and vox-adv-256.yaml, but are still a little confused.

2. which version of vox dataset is used to train these two model? There are 20,076 video clips in video-preprocessing/vox-metadata.csv, so maybe the two models are trained with these 20,076 video clips?

Thanks a again. Looking forwards to your replies.

**Comment by AliaksandrSiarohin** [comment]
1. Vox-cpk is a model trained without adversarial discriminator for 100 epochs. Vox-adv-cpk is Vox-cpk finetuned for another 50 epochs with adversarial discriminator. 
2. Yes both is trained on the same dataset described in vox-metadata.csv

**Comment by Honlan** [comment]
got it. thanks a lot.

**Comment by Honlan** [comment]
I am sorry to bother you again.

If I want to obtain vox-adv-cpk.pth.tar, then I should:

1. CUDA_VISIBLE_DEVICES=0,1,2,3 python run.py --config config/vox-256.yaml --device_ids 0,1,2,3
2. CUDA_VISIBLE_DEVICES=0,1,2,3 python run.py --config config/vox-adv-256.yaml --device_ids 0,1,2,3 --checkpoint CHECKPOINT

where CHECKPOINT is the checkpoint directory generated by step 1, so step 2 will load the model of step 1 and continue to train another 50 epochs.

Is that right?

Thanks again.

**Comment by AliaksandrSiarohin** [comment]
Yes. It is right.

**Comment by Honlan** [comment]
Hello~ I have downloaded the videos of vox and extracted the frame as png files.

In vox-256.yaml, I see that `num_epochs=100` and `num_repeats=75`. As there are about 3000 unique videos in vox, so an epoch contains `3000*75=225,000` samples, it that right?

Moreover, how long time did you spend on training with vox-256.yaml and vox-adv256.yaml respectively? I use 4 gpus for training.

Thanks again for your replies.

**Comment by Honlan** [comment]
#137 this issue seems to provide some useful information

**Comment by kenmbkr** [comment]
> Vox-cpk is a model trained without adversarial discriminator for 100 epochs. Vox-adv-cpk is Vox-cpk finetuned for another 50 epochs with adversarial discriminator.

@AliaksandrSiarohin Did you find any differences in performance if you train the adversarial model for 150 epochs directly instead of 100 epochs without adversarial first then fine-tune 50 epochs with adversarial?

**Comment by AliaksandrSiarohin** [comment]
@kenmbkr I didn't find much difference.

**Comment by fghjkllkh** [comment]
![image](https://user-images.githubusercontent.com/86365965/123117587-10e60a80-d46c-11eb-800d-35897e788751.png)
why ? :(
