### ISSUE TITLE
Fail to install torch==1.0.0

### ISSUE THREAD

**Issue by bigboss97** [AliaksandrSiarohin/first-order-model#129]
I'm using python 3.7.5 and got following error in installing requirements:
Collecting torch==1.0.0 (from -r requirements.txt (line 25))
  ERROR: Could not find a version that satisfies the requirement torch==1.0.0 (from -r requirements.txt (line 25)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.0 (from -r requirements.txt (line 25))
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Then I tried any torch version and got error while building:
PS E:\bin\first-order-model-master> pip install torch
Collecting torch
  Downloading https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz (128kB)
     |████████████████████████████████| 133kB 656kB/s
Collecting pyyaml (from torch)
  Downloading https://files.pythonhosted.org/packages/fb/aa/1a7ac452c52b93ab759d0b5b81c901ea122d95a5abf429decc660a44a2f1/PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216kB)
     |████████████████████████████████| 225kB 1.3MB/s
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error

**Comment by AliaksandrSiarohin** [comment]
Sorry, not familiar with windows. If you not target training any higher version of pytorch could be used.

**Comment by bigboss97** [comment]
I found something and tried it. That seems to work :-)
pip install torch==1.0.0 torchvision==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Zylvian** [comment]
> I found something and tried it. That seems to work :-)
> pip install torch==1.0.0 torchvision==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html

When running this, I end up not getting CUDA support with the torch call in the demo.

**Comment by lbux** [comment]
> > I found something and tried it. That seems to work :-)
> > pip install torch==1.0.0 torchvision==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html
> 
> When running this, I end up not getting CUDA support with the torch call in the demo.

Using conda and install pytorch made it work for me:

`conda install pytorch==1.0.0 torchvision==0.2.1 cuda100 -c pytorch`

You can try installing torch with pip and adding cuda100 to the command; however, I'm unsure if that will work as I have not tested it

**Comment by bigboss97** [comment]
> 
> 
> I found something and tried it. That seems to work :-)
> pip install torch==1.0.0 torchvision==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html

Unfortunately, that wasn't good enough. When I ran
`python crop-video.py  --inp MOV_3903.mp4`
It failed with:
`    raise AssertionError("Torch not compiled with CUDA enabled")`
`AssertionError: Torch not compiled with CUDA enabled`
Then I tried:
`pip install -f https://download.pytorch.org/whl/torch_stable.html torch==1.4.0`
\*snip\*
`Installing collected packages: torch`
`  Attempting uninstall: torch`
`    Found existing installation: torch 1.0.0`
`    Uninstalling torch-1.0.0:`
`      Successfully uninstalled torch-1.0.0`
`Successfully installed torch-1.4.0+cu92`
Now crop-video.py hits:
`    import imageio_ffmpeg`
`ModuleNotFoundError: No module named 'imageio_ffmpeg'`
\*snip\*
`    "To use the imageio ffmpeg plugin you need to "
ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'`
At least it's progressing  :-)

**Comment by tomathosauce** [comment]
> I found something and tried it. That seems to work :-)
> pip install torch==1.0.0 torchvision==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html

This worked for me, but I had to use the 64 bit version of Python instead of the 32 bit version.

**Comment by TheStickyStudio** [comment]
> > I found something and tried it. That seems to work :-)
> > pip install torch==1.0.0 torchvision==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html
> 
> Unfortunately, that wasn't good enough. When I ran
> `python crop-video.py --inp MOV_3903.mp4`
> It failed with:
> ` raise AssertionError("Torch not compiled with CUDA enabled")`
> `AssertionError: Torch not compiled with CUDA enabled`
> Then I tried:
> `pip install -f https://download.pytorch.org/whl/torch_stable.html torch==1.4.0`
> *snip*
> `Installing collected packages: torch`
> ` Attempting uninstall: torch`
> ` Found existing installation: torch 1.0.0`
> ` Uninstalling torch-1.0.0:`
> ` Successfully uninstalled torch-1.0.0`
> `Successfully installed torch-1.4.0+cu92`
> Now crop-video.py hits:
> ` import imageio_ffmpeg`
> `ModuleNotFoundError: No module named 'imageio_ffmpeg'`
> *snip*
> ` "To use the imageio ffmpeg plugin you need to " ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'`
> At least it's progressing :-)

Just install ffmppeg by using the pip then run it again
