### ISSUE TITLE
Model diverging when training in VoxCeleb

### ISSUE THREAD

**Issue by BaldrLector** [AliaksandrSiarohin/first-order-model#13]
Hi, thanks for your great work!

I am trying to retrain the method in VoxCeleb, I don't use GAN_loss.
Any try it and face the same issue with me?  
Is there any strategy in training or some problem with my dataset？ 
Any advice is appreciated.
Below is my result during the training.

![image](https://user-images.githubusercontent.com/19874480/75509607-41a66300-5a23-11ea-8706-1cf02efcd9ab.png)
![image](https://user-images.githubusercontent.com/19874480/75509673-73b7c500-5a23-11ea-8c83-d7024b3c22ea.png)
![image](https://user-images.githubusercontent.com/19874480/75509690-7ca89680-5a23-11ea-9a85-803117396bff.png)

Your reply will be appreciated.

**Comment by AliaksandrSiarohin** [comment]
Yes, this problem appears if you use pytorch 1.1 and higher.

**Comment by AliaksandrSiarohin** [comment]
Check related issue https://github.com/AliaksandrSiarohin/first-order-model/issues/4

**Comment by BaldrLector** [comment]
> Yes, this problem appears if you use Pytorch 1.1 and higher.

Thanks, I will try to change my PyTorch version and retrain it.

**Comment by BaldrLector** [comment]
I believe it problem of optional param: align_corners, as see in Pyotrch's document
 """ 
      align_corners (bool, optional): Geometrically, we consider the pixels of the
            input  as squares rather than points.
            If set to ``True``, the extrema (``-1`` and ``1``) are considered as referring
            to the center points of the input's corner pixels. If set to ``False``, they
            are instead considered as referring to the corner points of the input's corner
            pixels, making the sampling more resolution agnostic.
            This option parallels the ``align_corners`` option in
            :func:`interpolate`, and so whichever option is used here
            should also be used there to resize the input image before grid sampling.
            Default: ``True``
    .. warning::
        When ``align_corners = True``, the grid positions depend on the pixel
        size relative to the input image size, and so the locations sampled by
        :func:`grid_sample` will differ for the same input given at different
        resolutions (that is, after being upsampled or downsampled).
        The default behavior up to version 1.3.x is ``align_corners = True``.
        The default behavior will be changed to ``align_corners = False`` from
        v1.4.0, in order to bring it in line with the default for :func:`interpolate`.
   """

I use v1.4.0, the method does not diverging for now

**Comment by AliaksandrSiarohin** [comment]
This i'm not sure in #4  it has been reported that model fails with v1.4, also for me my other model fails.

**Comment by BaldrLector** [comment]
> This i'm not sure in #4 it has been reported that model fails with v1.4, also for me my other model fails.

My bad, I train two methods use v1.4, one method is diverging now. v1.4 still have problem

**Comment by BaldrLector** [comment]
I also try v1.1~1.4 and change the align_corners in those versions, no one works.
use pytorch v1.0.x  is the only solution for now.
thanks the author's response,  i will close this comment.

**Comment by BaldrLector** [comment]
Update: PyTorch v1.5 does not tackle this issue.
