### ISSUE TITLE
How to obtain 12331 training videos and 444 test videos from VoxCeleb?

### ISSUE THREAD

**Issue by kenmbkr** [AliaksandrSiarohin/first-order-model#136]
In [`vox-metadata.csv`](https://github.com/AliaksandrSiarohin/video-preprocessing/blob/master/vox-metadata.csv), there are 19550 video chunks for training (3354 unique `video_id`) and 525 video chunks (90 unique `video_id`) for testing. How do you obtain 12331 training videos and 444 testing videos as stated in the paper?

**Comment by Veselov-Ivan** [comment]
> In [`vox-metadata.csv`](https://github.com/AliaksandrSiarohin/video-preprocessing/blob/master/vox-metadata.csv), there are 19550 video chunks for training (3354 unique `video_id`) and 525 video chunks (90 unique `video_id`) for testing. How do you obtain 12331 training videos and 444 testing videos as stated in the paper?

Seems to be solved in https://github.com/AliaksandrSiarohin/video-preprocessing/issues/6#issuecomment-625406386

**Comment by kenmbkr** [comment]
Noted. Thank you for the reference.
