### ISSUE TITLE
RuntimeError: tensor should be 2 dimensional

### ISSUE THREAD

**Issue by tuugiiututu** [AliaksandrSiarohin/first-order-model#139]
Hello
I try dis project but it's not working show like this error 
"RuntimeError: tensor should be 2 dimensional"
how to fix it 
I used Windows 10 it's windows error or code or module idk pls guys someone know dis i installed all requirements

**Comment by AliaksandrSiarohin** [comment]
Wrong version of pytorch, I think.

**Comment by tuugiiututu** [comment]
ty i found it  
can i up resolution, quality and size prediction. how i do it

**Comment by AliaksandrSiarohin** [comment]
Guess you can try https://github.com/tg-bomze/Face-Image-Motion-Model

**Comment by tuugiiututu** [comment]
it's only 256x256 i'll plus pixels 460 or 720 so
can i do it and how i do

**Comment by AliaksandrSiarohin** [comment]
They use some upsampling method to increase the resolution. Otherwise not possible.
