### ISSUE TITLE
Pre-trained checkpoint corrupted?

### ISSUE THREAD

**Issue by avillanueva** [AliaksandrSiarohin/first-order-model#140]
I have tried to download the "vox-cpk.pth.tar" and "vox-adv-cpk.pth.tar" pre-trained checkpoints but I can not un-compress them. I get a corrupted file error no matter the decompression SW I use (winrar, 7-zip, ...).

Has anyone had the same problem?. Any suggestions?

Thanks

**Comment by AliaksandrSiarohin** [comment]
#122
