### ISSUE TITLE
Here is (I think) the pytorch 1.5 fix:

### ISSUE THREAD

**Issue by qasfb** [AliaksandrSiarohin/first-order-model#146]
https://github.com/pytorch/pytorch/issues/38985

See the workaround for 1/integer scales. 
modules.util.AntiAliasInterpolation2d can be patched until pytorch fixes the bug.

```
# out = F.interpolate(input_tensor, scale_factor=(scale, scale))
inv_scale = 1/scale
int_inv_scale = int(inv_scale)
assert(inv_scale == int_inv_scale)
out = input_tensor[:, :, ::int_inv_scale, ::int_inv_scale]
```

Let me know if that solves the divergence issue for you.

**Comment by AliaksandrSiarohin** [comment]
Yes, this indeed seems to work. Thank you.
