### ISSUE TITLE
Graphic card compatibility

### ISSUE THREAD

**Issue by aleksy** [AliaksandrSiarohin/first-order-model#147]
Hello there!

My question is if the program is suitable for PCs that only have Nvidia graphic cards, or do AMD support this program as well?
Yesterday I have encountered an error and it's about me not having Nvidia graphic card.
Neither native nor in docker I could make it run.

**Comment by AliaksandrSiarohin** [comment]
Yes, it need a cuda, which is nvidia library. You can use cpu or colab, if you don't have it.

**Comment by Zylvian** [comment]
When using colab, where does the compiling actually take place?

**Comment by AliaksandrSiarohin** [comment]
Python doesn't need compilation.

**Comment by Zylvian** [comment]
Sorry, I mean what resources does your Colab demo project use to make the video?

Also, here's something I made:
https://www.facebook.com/TheBestEmperor/posts/2827945487316041

**Comment by AliaksandrSiarohin** [comment]
This is an educational service from Google. So it uses Google gpus.

**Comment by Zylvian** [comment]
Btw, is there a way to config the colab files to accept formats other than 256x256, or is this problematic?

And are there different checkpoints for different uses, or is it all the same which one you use?

**Comment by AliaksandrSiarohin** [comment]
This is problematic and require retraining see related isssue #20.
Different checkpoints for different datasets (body, carton animals, etc). However for practical purposes only faces with vox-celeb checkpoint is useful currently.

P.S. Oblivion one of my favorite games.

**Comment by Zylvian** [comment]
Haha, well I'm glad I could use your hard work for something entertaining then! :D

I'm working on getting a competent setup to test this with, but as I'm running on Windows, I'm running into a bunch of problems. Right now I'm trying to use anaconda to enable cuda support with pytorch, as running it with ```cpu``` was not scalable, and I keep getting "Torch not compiled with CUDA enabled".

Also, when it comes to faces, how much "room" do I have to test in? With using your Colab demo, the only real different stuff I can vary are the ``make_animation()` parameters, but from what I've gathered it's mostly either doing relative or absolute replacements.
If you have any tips, I'll gladly listen! :D

**Comment by AliaksandrSiarohin** [comment]
Sorry but I'm not familiar with windows instalations, so can't help you. 
I only impliment the parameters in make_animation. But you can try to write a code for 
keypoint manipulation yourself. For example fix position of some keypoint and move others, or some movements from one video and others from another video.

**Comment by Zylvian** [comment]
For face transplants, i.e the Oblivion video, is it best to use taichi or taichi-adv?

**Comment by AliaksandrSiarohin** [comment]
Taichi is not for faces. You should use vox or vox-adv. No idea which is better.
