### ISSUE TITLE
good job,but i cant find "swap face.ipynb"

### ISSUE THREAD

**Issue by dayu1979** [AliaksandrSiarohin/first-order-model#15]
thank you,that's great work...

**Comment by AliaksandrSiarohin** [comment]
It is not yet released.
Sorry about that.

**Comment by 5agado** [comment]
Any updates on this? Is the release of the face-swap part still planned?

**Comment by dromomord** [comment]
> It is not yet released.
> Sorry about that.

Any update? Thx.

**Comment by AliaksandrSiarohin** [comment]
https://github.com/AliaksandrSiarohin/motion-cosegmentation
```
python part_swap.py --source_image ... --target_video ... --checkpoint vox-first-order.pth.tar --config config/vox-256-10segments.yaml --supervised --first_order_motion_model
```
