### ISSUE TITLE
Not working on fast-motion video

### ISSUE THREAD

**Issue by ayush9198gupta** [AliaksandrSiarohin/first-order-model#156]
Hi @AliaksandrSiarohin ,

I am using your model for image animation and tested on slow motion video and on cropped images it is working fine but not working on fast motion video or on fast lisping video.

I have also converted fast motion video into slow motion and tested but again results were distorted.

Kindly help to fix this for fast motion or fast lisping video to work fine.

Thanks

**Comment by AliaksandrSiarohin** [comment]
The method process video frame by frame so there should be no differece. Please provide an example.

**Comment by ayush9198gupta** [comment]
sure @AliaksandrSiarohin 

I have tested on fast motion video so here i am sharing my loom video on this with input and output results.
Kindly go through the loom video link:

https://www.loom.com/share/3407962fff2941f28f7d9aa27347abb2

Thanks in advance

**Comment by AliaksandrSiarohin** [comment]
The problem is that you did not crop your video. Crop it using crop-video.py script.

**Comment by ayush9198gupta** [comment]
ok @AliaksandrSiarohin  

I will check with this script and let you know

**Comment by ayush9198gupta** [comment]
Thanks its working.
