### ISSUE TITLE
pose results by provided checkpoint

### ISSUE THREAD

**Issue by CrossLee1** [AliaksandrSiarohin/first-order-model#157]
Hi, I download the provided checkpoint `"fashion.pth.tar"`, and run the following command:
`python demo.py --config config/fashion-256.yaml --driving_video data/fashion-videos/train/91eqrZs3NOS.mp4 --source_image data/fashion/test/A11unT+W2IS.mp4/frame000001.jpg --checkpoint fashion.pth.tar --relative --adapt_scale`. 
But I got unsatisfactory results, such as the videos and two poses below.
![result](https://user-images.githubusercontent.com/18067400/84734975-e352bf80-afd4-11ea-8e4f-cd075ca81d68.gif)
![result mp4_20200616_132705 055](https://user-images.githubusercontent.com/18067400/84735060-1a28d580-afd5-11ea-93f1-b565adc56989.jpg)
![result mp4_20200616_132743 382](https://user-images.githubusercontent.com/18067400/84735111-3f1d4880-afd5-11ea-9f9a-c77066ab9f60.jpg)

Is it normal, how can I improve the results.
Thanks

**Comment by AliaksandrSiarohin** [comment]
The results looks as expected. If you want to improve you can try to train using ground truth keypoints.

**Comment by CrossLee1** [comment]
Thanks for your advice, I'll try it :)
