### ISSUE TITLE
TaiChi's posture transfer cannot restore the desired effect

### ISSUE THREAD

**Issue by zhangqijun** [AliaksandrSiarohin/first-order-model#160]
[![ScreenShot](http://pc.zzz9958123.com:8082/images/2020/06/24/2020-06-24-1.56.58.png)](https://youtu.be/LWVIAM1GYlk)
from left to right. driven video, source image, res, res_adv
test video download from [first-order-model/data/taichi-loading/](https://github.com/AliaksandrSiarohin/first-order-model/tree/master/data/taichi-loading)
use command `python3 demo.py  --config config/taichi-256.yaml --driving_video driving --source_image source --checkpoint  taichi-checkpoint --relative --adapt_scale`
and show some strange results, such as four arms or twisted legs.

In order to get some more practical results, can you provide some good suggestions

**Comment by AliaksandrSiarohin** [comment]
The model for Taichi is not practically usefull, you are right. The obvious improvements would be using supervised keypoints and collecting larger dataset.
