### ISSUE TITLE
'ffmpeg' is not recognized

### ISSUE THREAD

**Issue by Kytol** [AliaksandrSiarohin/first-order-model#167]
Trying face alignment video cropping command in anaconda with:

ffmpeg -i driving_video/video.mp4 -ss 0.0 -t 7.316666666666666 -filter:v "crop=892:892:432:129, scale=256:256" crop.mp4

'ffmpeg' is not recognized  as an internal or external command, operable program or batch file.

Gives out that error. I added ffmpeg into advanced system environment path and still doesn't work.

This may be beginner problem, but any help would be welcome! :)

**Comment by AliaksandrSiarohin** [comment]
Yes, it is not on your path or you did not install it.
In the PATH you should add the folder where the executable is located. Not executable itself. Alternatively you can navigate to the folder with executable file and launch it from there.

**Comment by Kytol** [comment]
Okay, thanks didn't know that. I somehow solved this problem though, maybe with downloading latest python and/or restarting pc so all downloads worked properly with reset. Now, problems are with last stage, but that's for another day.
