### ISSUE TITLE
cropping_size config didn't match paper's size

### ISSUE THREAD

**Issue by FreedomGu** [AliaksandrSiarohin/first-order-model#175]
Hi, I want to make sure one thing. the new cropping size you offered (with increase_area version) is this the same original version with the paper setting? I think i did it but do not get correct size, especially with the stark picture, i changed increase_area from 0.1-0.3 but i cannot get similar result shown in your demo 
!
![starkcrop20](https://user-images.githubusercontent.com/42958381/86666161-289b5900-bfa5-11ea-82bb-047f80ec52d0.jpg)
![9676e744cf6c4c3decf334472f4bee5](https://user-images.githubusercontent.com/42958381/86666557-9051a400-bfa5-11ea-81d5-555a6216e01f.png)

**Comment by AliaksandrSiarohin** [comment]
I cropped the images in demo manually, using paint. In the paper this script is not used. I used the videos obtained from vox-celeb using video_prepricessing repository. I guess 0.1is what I used to preprocesd vox back there

**Comment by FreedomGu** [comment]
Thanx!
