### ISSUE TITLE
The perceptual loss can't convergence.

### ISSUE THREAD

**Issue by sadbb** [AliaksandrSiarohin/first-order-model#178]
Hi bro,
I run this model using `python run.py --config config/vox-256.yaml` with the vox dataset you gave me a few days ago. But the perceptual loss can't convergence, hovering at 300 all the time. This is my options:
batch_size: 14
trained for 18 hours on 2 NVIDIA 2080Ti GPUs.
The other Settings are the same as in your code. I would appreciate it if you could give me some advice.

**Comment by AliaksandrSiarohin** [comment]
You should use torch=1.0.0 as explained in readme.

**Comment by Anothorld** [comment]
I have the same problem
the loss descending normally at the start but after 3k or 4k steps the loss increase sharply
I checked the output
![image](https://user-images.githubusercontent.com/43511948/96871948-89dc2f00-14a5-11eb-82ba-bc362e0ce70f.png)

**Comment by AliaksandrSiarohin** [comment]
Use same solution then.
