### ISSUE TITLE
Error message when I try to read in my own image in Colab

### ISSUE THREAD

**Issue by aije-eg** [AliaksandrSiarohin/first-order-model#179]
Hi I get this error when I put in my own image in Colab.
Please can you help with going about it? I am sure it is a simple fix but I have been at it with trying different things and it wont work... Thank you
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/65262976/87207315-7de6ab80-c2c0-11ea-9bb1-66c8be9b1deb.png">

**Comment by AliaksandrSiarohin** [comment]
Your image is corrupted probably, try to open it with paint and save in jpg and png format.

**Comment by aije-eg** [comment]
Okay Thank you very much :)
