### ISSUE TITLE
Problems downloading the checkpoints

### ISSUE THREAD

**Issue by simplo** [AliaksandrSiarohin/first-order-model#18]
Hi, I downloaded all the checkpoints, both with simple download, both with the Yandex.Disk app, but all archives seems to be corrupted.
I tried to open them with WinRAR, 7zip and PeaZip, same result.
Can you please help me?
Thank you.

**Comment by AliaksandrSiarohin** [comment]
You should not open them.
Use - - checkpoint something.pth.tar

**Comment by simplo** [comment]
THank you!
