### ISSUE TITLE
Generated Video Frame Rate 

### ISSUE THREAD

**Issue by 0x4Mio** [AliaksandrSiarohin/first-order-model#181]
Hi
The frame rate of the generated video is 10 frames per second. How to increase the frame rate to 30 fps?

**Comment by AliaksandrSiarohin** [comment]
imageio.mimsave(..., fps=30)

**Comment by videoprice** [comment]
Please, call the file of this string - imageio.mimsave(..., fps=30)

**Comment by gentle1212** [comment]
> imageio.mimsave(..., fps=30)

kindly let me know in which folder and file I have to add this line of code to increase fps.
