### ISSUE TITLE
Error in crop-video.py

### ISSUE THREAD

**Issue by mhsteppan** [AliaksandrSiarohin/first-order-model#190]
I came across an error message, when trying to run crop-video.py. The error message reads:

File "crop-video.py", line 70
scale = f'{image_shape[0]}:{image_shape[1]}'
                                               ^
SyntaxError: invalid syntax

I am wondering how to fix it. 
Many thanks,
Martin

**Comment by AliaksandrSiarohin** [comment]
You need python 3.6 or higher.

**Comment by mhsteppan** [comment]
thank you!
