### ISSUE TITLE
num_blocks for higher res training

### ISSUE THREAD

**Issue by eps696** [AliaksandrSiarohin/first-order-model#191]
hello, 
what is the correspondence between `num_blocks`, `num_down_blocks`, `num_bottleneck_blocks` and the model resolution?
should i add 1 to all `num_blocks` and `num_down_blocks` (keeping `num_bottleneck_blocks` the same) to properly double the resolution (e.g. from 64x64 to 128x128)?

**Comment by AliaksandrSiarohin** [comment]
No idea, try both.
