### ISSUE TITLE
face swap performance

### ISSUE THREAD

**Issue by Mohamed209** [AliaksandrSiarohin/first-order-model#193]
how get optimal results in face swap task like in the repo readme , for example i am swapping monalisa face with attached video but results not like demo proposed , am i missing something

src image : 
![mona](https://user-images.githubusercontent.com/12018493/88396943-86aca680-cdc3-11ea-82c0-b85f613ecf88.jpg)

target video : 
https://drive.google.com/file/d/1f4tnW9se28LGt0aQ-mF-depYnAoLoj9v/view?usp=sharing

result : https://drive.google.com/file/d/1fRxehjOvb6iqiyfePgNzC8Pu6e4i_xWm/view?usp=sharing

cmd used : `!python part_swap.py --source_image /kaggle/input/srcimgs/mona.jpg --target_video /kaggle/input/targetvidz/target.mp4 --checkpoint weights/vox-first-order.pth.tar --config config/vox-256-sem-10segments.yaml --supervised --first_order_motion_model`

**Comment by AliaksandrSiarohin** [comment]
You did not specify proper segments ```--swap_index 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15```
