### ISSUE TITLE
How to change output video codec?

### ISSUE THREAD

**Issue by megapro17** [AliaksandrSiarohin/first-order-model#208]
So by default the demo.py outputting result.mp4 which is x264, crf 25, 256x256 video. But how to change these paramethers? I run a search across all files but didn't find anything. Can anyone help me with that? 
Higher res video should look better even with 256x256 pictures, because of motion
Also, crf is too high
Seems like it only saves video here, and encoding done somewhere else
`imageio.mimsave(opt.result_video, [img_as_ubyte(frame) for frame in predictions], fps=fps)`

**Comment by megapro17** [comment]
@AliaksandrSiarohin why are you ignoring me?

**Comment by AliaksandrSiarohin** [comment]
```imageio.help('.mp4')```
