### ISSUE TITLE
motion-cosegmentation

### ISSUE THREAD

**Issue by DereWah** [AliaksandrSiarohin/first-order-model#210]
Hi,
In a point you said it is possible to face-swap and that we should check the motion-cosegmentation git for more reference.

I have installed all the motion-cosegmentation repo on a new env and a new directory, but to get it to work with the --first_order_motion_model and --supervised which config should I use? I've tried with different combinations (using the vox-first-order.pth.tar dataset you added in the google drive and segmentation config, etc).

Thank you, nice work on this!

**Comment by AliaksandrSiarohin** [comment]
Hi, see #193

**Comment by DereWah** [comment]
Thank you for the response. I also get this error while doing as in #193 

Traceback (most recent call last):
File "part_swap.py", line 233, in <module> face_parser = load_face_parser(opt.cpu)
File "part_swap.py", line 139, in load_face_parser from face_parsing.model import BiSeNet
ModuleNotFoundError: No module named 'face_parsing'

**Comment by AliaksandrSiarohin** [comment]
```For the reference we also provide fully-supervised segmentation. For fully-supervised add --supervised option. And run git clone https://github.com/AliaksandrSiarohin/face-makeup.PyTorch face_parsing which is a fork of @zllrunning.```
You did not pull or pull in a wrong folder. Should be incide motion_cosegmentation

**Comment by DereWah** [comment]
Got it to work, thank you!
Good job on all those repos, keep it up :)
