### ISSUE TITLE
Problem when aligning faces

### ISSUE THREAD

**Issue by grps88** [AliaksandrSiarohin/first-order-model#211]
Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 134, in process_video
    raise (e)
  File "crop-video.py", line 96, in process_video
    bboxes =  extract_bbox(frame, fa)
  File "crop-video.py", line 22, in extract_bbox
    bboxes = fa.face_detector.detect_from_image(frame[..., ::-1])
  File "C:\Users\filip\anaconda3\envs\FOM\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 36, in detect_from_image
    bboxlist = bboxlist[keep, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

any help? I've no idea what is wrong

**Comment by AliaksandrSiarohin** [comment]
If you post an issue you should specify all the details, what video was used, when the problem appear and so on.

**Comment by grps88** [comment]
I picked this video https://www.youtube.com/watch?v=NDjDgvXlfVw and used the python script to crop the face in the middle of the video; it went for a bit but then the error above appeared

this is the one I'm talking about: `python crop-video.py --inp driving_video/1.mp4`

**Comment by AliaksandrSiarohin** [comment]
Have other video work for you? What version of torch you are using?

**Comment by grps88** [comment]
One video gave no error but also didn't print the commands for ffmpeg, the pytorch i'm using is v.1.6.0 as 1.0.0 didn't install for me on Python 3.6

**Comment by AliaksandrSiarohin** [comment]
There are some problems with the end of this video, you some frames from the end. I got the following output
```
1410it [03:12,  7.32it/s]
ffmpeg -i 4.mp4 -ss 9.8 -t 5.699999999999999 -filter:v "crop=495:470:81:0, scale=256:256" crop.mp4
ffmpeg -i 4.mp4 -ss 23.0 -t 13.966666666666669 -filter:v "crop=449:470:127:0, scale=256:256" crop.mp4
ffmpeg -i 4.mp4 -ss 37.0 -t 9.966666666666669 -filter:v "crop=500:441:21:0, scale=256:256" crop.mp4
```

**Comment by grps88** [comment]
Alright thank you so much
