### ISSUE TITLE
RuntimeError: imageio.mimread() has read over 256 MiB of image data

### ISSUE THREAD

**Issue by 1FireXY1** [AliaksandrSiarohin/first-order-model#214]
the first time i did this it didnt have problems but now its keeps coming up with this when trying to load the pic and video next to each other.

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-aa2e607f879a> in <module>()
     10 
     11 source_image = imageio.imread('/content/gdrive/My Drive/first-order-motion-model/02.png')
---> 12 driving_video = imageio.mimread('/content/gdrive/My Drive/first-order-motion-model/04.mp4')
     13 
     14 #Resize image and video to 256x256

/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py in mimread(uri, format, memtest, **kwargs)
    305             ims[:] = []  # clear to free the memory
    306             raise RuntimeError(
--> 307                 "imageio.mimread() has read over 256 MiB of "
    308                 "image data.\nStopped to avoid memory problems."
    309                 " Use imageio.get_reader() or memtest=False."

RuntimeError: imageio.mimread() has read over 256 MiB of image data.
Stopped to avoid memory problems. Use imageio.get_reader() or memtest=False.

Any help?

**Comment by 1FireXY1** [comment]
update: making the video shorter fixed it but idk why it worked the first time then

**Comment by AliaksandrSiarohin** [comment]
Add memtest=False as written.

**Comment by alessiapacca** [comment]
Hey @AliaksandrSiarohin I added memtest=False, and it didn't give me that error anymore.
However, now I get a new one:
  
```
File ".../frames_dataset.py", line 104, in __getitem__
    path = np.random.choice(glob.glob(os.path.join(self.root_dir, name + '*.mp4')))
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty
```

the only thing I changed was addid memtest=False at line 43 of frames_dataset.py

```
 elif name.lower().endswith('.gif') or name.lower().endswith('.mp4') or name.lower().endswith('.mov'):
        video = np.array(mimread(name, memtest=False))
```
what could be the error here?

**Comment by AliaksandrSiarohin** [comment]
If you are training on your own dataset with different naming than mine you should specify id_sample: False.
