### ISSUE TITLE
Can't Build freetype or png on Windows with requirements.txt

### ISSUE THREAD

**Issue by FluorescentGreen5** [AliaksandrSiarohin/first-order-model#219]
Everytime I run `pip install -r requirements.txt`, I get this error:

```
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
```

- I am using 64-bit Python.
- I have installed freetype and libpng from gnuwin32.
- I have installed `python-dev-tools`.
- I have restarted Windows after doing the above.

I've noticed other people here have had issues getting this repo to work on Windows, but haven't seen anyone directly ask about this specific error.

**Comment by hastydev** [comment]
try python -m pip install -U matplotlib with wheel

**Comment by hastydev** [comment]
Matplotlib? If yes, try python -m pip install -U matplotlib

**Comment by FluorescentGreen5** [comment]
Yep, `pip install -U matplotlib` did the trick. Thanks.
