### ISSUE TITLE
Issue with "Load driving video and source image" "RuntimeError: Frame is 0 bytes...."

### ISSUE THREAD

**Issue by taquito118** [AliaksandrSiarohin/first-order-model#221]
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py in _read_frame_data(self)
    620                     raise RuntimeError(
--> 621                         "Frame is %i bytes, but expected %i." % (len(s), framesize)
    622                     )

RuntimeError: Frame is 0 bytes, but expected 196608.

During handling of the above exception, another exception occurred:

CannotReadFrameError                      Traceback (most recent call last)
5 frames
/usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py in _read_frame_data(self)
    626                 err2 = self._stderr_catcher.get_text(0.4)
    627                 fmt = "Could not read frame %i:\n%s\n=== stderr ===\n%s"
--> 628                 raise CannotReadFrameError(fmt % (self._pos, err1, err2))
    629             return s, is_new
    630 

CannotReadFrameError: Could not read frame 835:
Frame is 0 bytes, but expected 196608.

I made sure both files are 256x256. Kept getting the same error.
Any ideas on how to fix this? 

By the way, good job on the script.

**Comment by gogED** [comment]
same problem here, how did you fix it?

**Comment by taquito118** [comment]
A specific video i was using that wasn't working. I had to download that video from a youtube tutorial that shows how to use it and it worked. My guess is that maybe the video is too big in file size? 
I'm mostly likely wrong.
