### ISSUE TITLE
Is the checkpoint for the Bair dataset a wrong file?

### ISSUE THREAD

**Issue by kenmbkr** [AliaksandrSiarohin/first-order-model#224]
I ran the following command and got results like [this](https://streamable.com/ub2oxi).
`python run.py --config config/bair-256.yaml --mode reconstruction --checkpoint checkpoints/bair-cpk.pth.tar`

I used the same environment and the corresponding commands for VoxCeleb checkpoints and they work fine like [this](https://streamable.com/zsa2t9).
`python run.py --config config/vox-256.yaml --mode reconstruction --checkpoint checkpoints/vox-cpk.pth.tar`

EDIT: I think the link to the Bair dataset in the README.md is the wrong one, not the checkpoint. In the reconstruction results, the generator attempts to inpaint a red and black robot arm, which corresponds to the results shown in the supplementary material. I looked at all the testing videos in the Bair dataset from README.md and there are no videos with the red and black robot arm. Instead, all the videos have only the grey robot arm with the light blue circle. Could you kindly upload the Bair dataset used in the paper? Thank you.

**Comment by AliaksandrSiarohin** [comment]
Yes, the video your used is from a different dataset. You download it from this link https://yadi.sk/d/66vNK0EwJcVkPg

**Comment by kenmbkr** [comment]
> Yes, the video your used is from a different dataset. You download it from this link https://yadi.sk/d/66vNK0EwJcVkPg

@AliaksandrSiarohin I downloaded the dataset again and it is still the one with the grey robot arm with the light blue circle, not the red and black robot arm as in your supplementary materials. Could you please double check the link?

**Comment by kenmbkr** [comment]
@AliaksandrSiarohin I followed the citation in the paper and found the [link](https://sites.google.com/view/sna-visual-mpc) to download the Bair dataset for the Sawyer robotic arm, but the data is in TFRecord format. Do you have a script to extract the raw videos from the TFRecord or could you kindly upload the raw videos of the Sawyer robotic arm to Yandex Disk?

**Comment by AliaksandrSiarohin** [comment]
Try this link https://yadi.sk/d/Rr-fjn-PdmmqeA

**Comment by kenmbkr** [comment]
Thank you. It works.
