### ISSUE TITLE
Pretrained checkpoints exceeded a download quota, are there any alternatives?

### ISSUE THREAD

**Issue by ghost** [AliaksandrSiarohin/first-order-model#225]
The pretrained checkpoints provided on the README file cannot be downloaded any more.
Are there any alternatives for a reference? Thank you.

Download URL: https://drive.google.com/drive/folders/1PyQJmkdCsAkOYwUyaj_l-l0as-iLDgeH

The Error Message

```
Download quota exceeded for this file, so you can't download it at this time.
```

**Comment by AliaksandrSiarohin** [comment]
Yandex disk.

**Comment by ghost** [comment]
Thank you for your reply.
I tried, yet, the download speed from yandex disk on my end was super slow, it estimated 20+ hours to download a file (289MB).

**Comment by z83rulek** [comment]
you can copy it, and than download from your own drive
![image](https://user-images.githubusercontent.com/21211498/89878510-396a6a80-dbf4-11ea-85b1-8885ccd19d8a.png)
![image](https://user-images.githubusercontent.com/21211498/89878629-5c951a00-dbf4-11ea-8860-a95458ef635e.png)

**Comment by ghost** [comment]
@z83rulek Thanks for the suggestion, problem resolved.
