### ISSUE TITLE
Is any other place to download the checkpoints

### ISSUE THREAD

**Issue by guazike** [AliaksandrSiarohin/first-order-model#23]
It's too slow when downloading cpk form Yandex.Disk

**Comment by AliaksandrSiarohin** [comment]
What checkpoints you need, vox-celeb you can download from google-drive https://drive.google.com/open?id=1kZ1gCnpfU0BnpdU47pLM_TQ6RypDDqgw

**Comment by guazike** [comment]
thanks

**Comment by dylankilkenny** [comment]
i am trying to download the vox-cpk.pth.tar checkpoint but yandex requires a russian phone number for me to download, which i dont have. Could you possibly upload elsewhere?

**Comment by AliaksandrSiarohin** [comment]
Vox celeb checkpoint is also on goole drive
https://drive.google.com/open?id=1kZ1gCnpfU0BnpdU47pLM_TQ6RypDDqgw

**Comment by filipppp** [comment]
How can I extract them 7Zip and Winrar cant read it and report it as a broken archive

**Comment by AliaksandrSiarohin** [comment]
See #18

**Comment by dylankilkenny** [comment]
the google drive link only contains images and mp4s

**Comment by AliaksandrSiarohin** [comment]
Search for vox-cpk.pth.tar

**Comment by ihunter** [comment]
Can I get the fashion checkpoint on Google Drive as well?

**Comment by AliaksandrSiarohin** [comment]
I will upload checkpoints here https://drive.google.com/open?id=1PyQJmkdCsAkOYwUyaj_l-l0as-iLDgeH
