### ISSUE TITLE
about gaussian heatmap?

### ISSUE THREAD

**Issue by maliho0803** [AliaksandrSiarohin/first-order-model#24]
in monkey net, you will calculate Covariance of heatmap, but this improved work, i find that you just using a constant variance, could you explain me why?

**Comment by AliaksandrSiarohin** [comment]
In monkey-net this was supposed to represent some keypoint scale, in first order model I found more efficient way to represent the scale and rotation of the keypoint which is jacobians. Also constant variance make it more stable.

**Comment by maliho0803** [comment]
thank you very much! very impressive work!!!
