### ISSUE TITLE
maybe some generated videos are not very smooth?

### ISSUE THREAD

**Issue by maliho0803** [AliaksandrSiarohin/first-order-model#25]
do you think about smoothing the optical flow among frames, because some generated video may be not very natured?

**Comment by CarolinGao** [comment]
Can u show me one of your test videos? When I use such video, it stuck and I  am confused that whether the model  just  work  on small video?
[mayun.zip](https://github.com/AliaksandrSiarohin/first-order-model/files/4364771/mayun.zip)

**Comment by maliho0803** [comment]
i think you should crop you video, the video may not get good results.
