### ISSUE TITLE
Can't seem to run demo file with mgif checkpoint

### ISSUE THREAD

**Issue by gbernal** [AliaksandrSiarohin/first-order-model#251]
Hi @AliaksandrSiarohin, first of all, thank you and your colleagues for sharing the code.
This might be a trivial question but I can't seem to be able to run the demo with the mgif model. I'm interested in the animation portion of your work. when I run this` python demo.py  --config config/mgif-256.yaml --driving_video data/moving-gif/00002.gif --source_image data/souceImage/dino2.png --checkpoint checkpoints/mgif-cpk.pth.tar --relative --adapt_scale`
I get the following error. 
```
Traceback (most recent call last):
  File "demo.py", line 133, in <module>
    fps = reader.get_meta_data()['fps']
KeyError: 'fps'
```
What am I doing wrong? thank you in advanced

**Comment by AliaksandrSiarohin** [comment]
.gif dont have fps property
replace with 
```
fps=5
```

**Comment by gbernal** [comment]
Thank you so much, that did it!
