### ISSUE TITLE
Minimum amount of VRAM needed for using vox-celeb with parameters.

### ISSUE THREAD

**Issue by KMielnik** [AliaksandrSiarohin/first-order-model#257]
Hi, I have a question regarding the minimum requirement for using vox-celeb model (with optional parameters as ```--find_best_frame``` or cropping driving video first).

Has anyone successfully ran it on GPU with home user amount of VRAM? (4-8GB)
I have been tinkering with this repo, I'm creating a simpler version just for my use case, but I have tested it only on CPU and Google colab, where it takes 11-13 GB of VRAM, which makes me wonder if there's a way to run it (just the video generation/cropping) on consumer NVIDIA GPU which I'm planning to buy (6-8GB VRAM).

Or maybe someone knows a way for me to test it by myself on colab? (limiting VRAM available)

Thank you in advance.

**Comment by AliaksandrSiarohin** [comment]
I was running it on 2 gb gpu.

**Comment by KMielnik** [comment]
Amazing, thanks.
