### ISSUE TITLE
i think maybe the keypoint detector need to be improved? 

### ISSUE THREAD

**Issue by maliho0803** [AliaksandrSiarohin/first-order-model#26]
in some case, the key points is not stable,this will cause unreal transform in the neighbour of the point? do you have any good idea to improve this?

**Comment by AliaksandrSiarohin** [comment]
Hard to say without examples. The simplest thing is to supervise keypoints with some open-pose keypoints.

**Comment by maliho0803** [comment]
> Hard to say without examples. The simplest thing is to supervise keypoints with some open-pose keypoints.
please check the attachment, thank you! and did you try the supervised keypoints detector?
[result.zip](https://github.com/AliaksandrSiarohin/first-order-model/files/4386065/result.zip)

**Comment by AliaksandrSiarohin** [comment]
In this particular example you can try to flip vertically source image (to make it aligned with driving) and crop images more, to have only the face without shoulders like in README.md.

**Comment by maliho0803** [comment]
[result.zip](https://github.com/AliaksandrSiarohin/first-order-model/files/4386757/result.zip)
i think there are some bugs, please check the attachment .

**Comment by maliho0803** [comment]
[result.zip](https://github.com/AliaksandrSiarohin/first-order-model/files/4386805/result.zip)
please check the results in the attachment, maybe something wrong.

**Comment by AliaksandrSiarohin** [comment]
There is an artifact in the end of the video, but this is expected since talking people from vox-celeb never do the movements like this, so this is a generalization error. You should train with videos that contain similar movements in order to handle such movements.

**Comment by maliho0803** [comment]
> There is an artifact in the end of the video, but this is expected since talking people from vox-celeb never do the movements like this, so this is a generalization error. You should train with videos that contain similar movements in order to handle such movements.

yes, i think so, thank you very much! can you tell me how did you crop the videos during training?

**Comment by AliaksandrSiarohin** [comment]
The scripts is here https://github.com/AliaksandrSiarohin/video-preprocessing
There is also details about it in the paper.

**Comment by maliho0803** [comment]
> The scripts is here https://github.com/AliaksandrSiarohin/video-preprocessing
> There is also details about it in the paper.

thank you
