### ISSUE TITLE
should I add sn:True in fashion-256.yaml to use Spectral Norm?

### ISSUE THREAD

**Issue by leeacord** [AliaksandrSiarohin/first-order-model#264]
Hi, I have a question.

According to the following setting, Spectral Norm is not used in the discriminator of fashion-256.
https://github.com/AliaksandrSiarohin/first-order-model/blob/78079d14396052dea55a1ee6a4432fb13da61c53/config/fashion-256.yaml#L34-L39

But I found the following keys in the discriminator of ckpt file. Should I add ```sn:True```  in fashion-256.yaml to use Spectral Norm?
```python
import torch
checkpoint = torch.load('/content/fashion.pth.tar', map_location=torch.device('cpu'))
[i for i in checkpoint['discriminator'].keys()]
"""output
 'discs.1.down_blocks.0.conv.weight_orig',
 'discs.1.down_blocks.0.conv.weight_u',
 'discs.1.down_blocks.0.conv.weight_v',
 ......
"""
```

**Comment by AliaksandrSiarohin** [comment]
For what purpose, you are trying to retrain? If so this does not make any difference according to my observations, if you only want to run demo discriminator is not used.

**Comment by leeacord** [comment]
@AliaksandrSiarohin 
Thank you for your reply. I want to train the model from scratch. I am confused about whether sn should be set to False according to the configuration file fashion-256.yaml or set to True according to the corresponding pre-trained model. Maybe I can use spectral norm regularization, which may make training more stable.

**Comment by AliaksandrSiarohin** [comment]
Sure you can use it, but there won't be much difference.
