### ISSUE TITLE
How to test Taichi animation?

### ISSUE THREAD

**Issue by dypromise** [AliaksandrSiarohin/first-order-model#27]
Hi!
I follow the Google-Colab ipynb to test the model, found that there only exist face animation. So I dont know how to test taichi model, i noticed that git's repo have a crop_video.py and AUTHOR say we should crop image and video before test model, but I dont kown how to crop video for taichi model? and is there any precautions of driving video? thanks for any reply

**Comment by AliaksandrSiarohin** [comment]
I didn't prepare scripts for Taichi. But the videos from train dataset is cropped using https://github.com/AliaksandrSiarohin/video-preprocessing/blob/master/crop_taichi.py you can try to adapt this script. Or just plug  some detector from detectron2 into the crop-video.py.

**Comment by dypromise** [comment]
Thank you so much

**Comment by JasonBoy1** [comment]
I met this problem too, is there any solution?  Thanks. @AliaksandrSiarohin
