### ISSUE TITLE
Both .tar files have exceeded the quota for downloading, copying or shortcut, can you provide mirrors

### ISSUE THREAD

**Issue by Dawgmastah** [AliaksandrSiarohin/first-order-model#276]
As in title, cannot get my hands on the files because of quota exceeded

Thanks!

**Comment by AliaksandrSiarohin** [comment]
You can use yandex disk

**Comment by hhuyujie** [comment]
when i use yandex disk to download, i can't untar these files. It always shows Unknown format or Corrupted data.

**Comment by AliaksandrSiarohin** [comment]
It is not archives so not supposed to be untared. Use it as is.
