### ISSUE TITLE
Image quality degradation

### ISSUE THREAD

**Issue by borismus** [AliaksandrSiarohin/first-order-model#278]
My goal is to do style transfer on a face within a larger image, animate the face, and then bring it back into the original image.

Running the model seems to introduce image quality reduction. The result is that the image doesn't blend well when re-introduced into its original context. You can see a clear border. 

I'm wondering where this might be coming from, and if it can be mitigated. See the attached image. On the left is the original input image, and on the right is a snapshot of the output.

<img width="673" alt="Screen Shot 2020-09-14 at 9 03 51 PM" src="https://user-images.githubusercontent.com/277632/93164381-36203e00-f6ce-11ea-8ae4-dc66dd820764.png">

Any pointers appreciated,
-b

**Comment by AliaksandrSiarohin** [comment]
You mean on the top, where there a black line? The model is not trained with such black lines so it consider it as a background and draw a head on top of it. You can just add this black line manually after the generation.

**Comment by borismus** [comment]
Good call about the top line. That's something we can easily fix in post :) 

I actually meant more subtle image quality issues like blurring. I think they were caused by ffmpeg compositing, which I've now addressed with the `format=rgba` filter. 

```
ffmpeg -loop 1 -i '$context_path' -i '$lip_path' -filter_complex "\
   [1:v] format=rgba [fg]; \
   [0:v] format=rgba [bg]; \
   [bg][fg] overlay=$left:$top:shortest=1 \
   " -y '$final_path' 
```
