### ISSUE TITLE
A size mismatch error on fashion dataset after fixing bug of Imageio using solutions in #197

### ISSUE THREAD

**Issue by JialeTao** [AliaksandrSiarohin/first-order-model#290]
Hi, I followed the issue #197 to fix the bug of imageio by modifiying line 44 of the snippet codes. And run:

CUDA_VISIBLE_DEVICES=0,1 python run.py --config config/fashion-256.yaml --device_ids 0,1

And I got this error of size mismatch of fashion dataset. Do you have any suggestions? 

![image](https://user-images.githubusercontent.com/38600167/94331798-047a7180-0002-11eb-9fdf-407033e3799b.png)

**Comment by JialeTao** [comment]
It seems the auto-indent of the snippet is in trouble and I made a screen shot here.
![image](https://user-images.githubusercontent.com/38600167/94248669-5f07c500-ff51-11ea-9077-2adbc48b1ef2.png)

**Comment by AliaksandrSiarohin** [comment]
Can you print the shape of the video returned from this function?

**Comment by JialeTao** [comment]
> Can you print the shape of the video returned from this function?

Hi, the shape of the video returned from this funcshtion seems to be various.
![image](https://user-images.githubusercontent.com/38600167/94388588-17b34b80-0180-11eb-8e81-2b5d1ea95d81.png)

**Comment by AliaksandrSiarohin** [comment]
So you should resize it to the same size.

**Comment by JialeTao** [comment]
> So you should resize it to the same size.

Yeah, note that in frame_dataset.py, no crop or resize operaion is done for the frames, only the flip and jitter parameters are not none. While I remember all videos are cropped to 256*256 in the paper, does that mean I should resize the frame to 256 or another size and then crop to 256?

**Comment by AliaksandrSiarohin** [comment]
You can resize videos prior to training (with some script) , or during the training after frame selection (by adding call to resize function).

**Comment by JialeTao** [comment]
Thanks for quick reply. Yeah, but my question is which size to resize the video. And I noted in the FOMM paper, video is resize to 256*256, while in your provided code(or line 44 in the screen shot I provided), no resize operation is done.

---Original---

**Comment by AliaksandrSiarohin** [comment]
If you want to replicate the staff I did, use this script https://github.com/AliaksandrSiarohin/first-order-model/issues/86#issuecomment-610226113 to preprocess the data.

**Comment by JialeTao** [comment]
That works! Thanks very much!



---Original---
