### ISSUE TITLE
Changing scikit image resize function results in unexpected output

### ISSUE THREAD

**Issue by Mohamed209** [AliaksandrSiarohin/first-order-model#294]
In the main pipeline source image and driving video are resized to (256,256) using `resize` method from `skimage`
Also in script `crop_video.py` the same method is used to resize video frames before face detection and alignment , I noticed that resize from skimag is somehow slow , so I tried to use ffmpeg to resize the original video to (256,256) then send it to cropping stage , process was blazing fast , then the resulting cropped video was fed to the generation pipeline (key points detector+dense motion+generator) , resulting video was very weird ,
When reverting back to resize with scikit image results are good

Check cropping results using ffmpeg and resized with ffmpeg not skimag
[]()https://drive.google.com/file/d/1--5sVeYZ5ijZ3bsxwa3JFkM6qLGWMODr/view?usp=drivesdk

Cropping results seems optimal

But generated video has something wrong

[]()https://drive.google.com/file/d/1uLcT6SZp-Rv6dz_MEERr1mMYelpb56Ax/view?usp=drivesdk

**Comment by AliaksandrSiarohin** [comment]
You should convert to [0,1] range, e.g. img_to_float.

**Comment by Mohamed209** [comment]
So cropping is good ? , And if so while reading cropped video each frame pixels should be between [0:1] , or do you mean [0:1] with resize skimag will speed up the process

**Comment by Mohamed209** [comment]
great , I normalized every frame before sending to generation [0,1] , got the correct results
