### ISSUE TITLE
 __init__() got an unexpected keyword argument 'estimate_jacobian'

### ISSUE THREAD

**Issue by howardgriffin** [AliaksandrSiarohin/first-order-model#3]
Hi，when I downloaded your checkpoint/fashion.pth.tar and 'python demo.py', I encountered this problem.
Traceback (most recent call last):
  File "demo.py", line 92, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint)
  File "demo.py", line 28, in load_checkpoints
    **config['model_params']['common_params'])
TypeError: __init__() got an unexpected keyword argument 'estimate_jacobian'
Would you please tell me how to solve it?

**Comment by howardgriffin** [comment]
When I run run.py, the problem appears again.

**Comment by AliaksandrSiarohin** [comment]
What is precise command that you use?

**Comment by howardgriffin** [comment]
python demo.py --config config/fashion-256.yaml \
               --driving_video xxx.mp4 \
               --source_image xxx.jpg \
               --checkpoint checkpoint/fashion.pth.tar \
               --relative \
               --adapt_scale \

**Comment by AliaksandrSiarohin** [comment]
This was some re-factoring error.  Try to pull a new version.

**Comment by howardgriffin** [comment]
It works! Thank you!
