### ISSUE TITLE
error - demo.py

### ISSUE THREAD

**Issue by Kubakowal** [AliaksandrSiarohin/first-order-model#31]
After I ran that command: 
sudo python demo.py  --config config/vox-adv-256.yaml --driving_video ja.mp4 --source_image michal.png --checkpoint vox-adv-cpk.pth.tar --relative --adapt_scale

I got that error: 
File "demo.py", line 27
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                                                                    ^
SyntaxError: invalid syntax

**Comment by AliaksandrSiarohin** [comment]
You should use python3

**Comment by Kubakowal** [comment]
> You should use python3

But after I ran command with python3 I got another error: 
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'

**Comment by AliaksandrSiarohin** [comment]
You should install the requirements.txt, I suggest you to use google colab demo.ipynb. It is much easier.

**Comment by Kubakowal** [comment]
> olab demo.ipynb

Thanks for help, i will try to figure it out tomorrow.
