### ISSUE TITLE
Understanding about keypoints

### ISSUE THREAD

**Issue by zoezhu** [AliaksandrSiarohin/first-order-model#312]
Thank you for your great work first! But I have some puzzle about keypoints in this model. 

I know keypoints here are motion-specific, and in my understanding, one specific keypoint in different images represent the same face location (in voxCeleb for example). But in the visualization as following, why the same keypoint in different faces locate in different face position? (Red arrows for same green keypoints for example)
Is the model performance not that good, or I misunderstanding these keypoints? Please correct me if I miscomprehend this part. 

Thanks!

![25](https://user-images.githubusercontent.com/18457244/96952062-7fab4680-1520-11eb-995e-14793c4a2794.png)

**Comment by AliaksandrSiarohin** [comment]
The number of keypoints that I selected was 10,which is a bit random. So this keypoint is most likely does not represent anything and it is redundant. But in general it is not granted that all the keypoint have perfect meaning to human.

**Comment by zoezhu** [comment]
That make sense, thank you!

**Comment by Bovey0809** [comment]
I am trying to visualize the keypoints on my own images as what you had presented in the paper, the output of the kp_detector is a dict with key "values", I want to assign the 10 points to my image, what kind of scale factor should I use? I tried to multiply the points by 256, but the points are not stick to the face.  

I'm really happy playing with the model, thanks for you great work.

```python
kp_source = kp_detector(image)
plt.scatter(kp_source['value'])
```

**Comment by AliaksandrSiarohin** [comment]
They are in range [-1,1], so you should multiply by 127.5 and add 127.5

**Comment by Bovey0809** [comment]
> They are in range [-1,1], so you should multiply by 127.5 and add 127.5

Thanks, I can visualize the points now.

**Comment by SURABHI-GUPTA** [comment]
@AliaksandrSiarohin I did what you said above but still some points are outside.
![image_kp](https://user-images.githubusercontent.com/22388014/118085465-13bafd80-b3e0-11eb-9990-59113a5237e8.png)

**Comment by AliaksandrSiarohin** [comment]
I guess, you invert x and y axis.
