### ISSUE TITLE
Some inputs seem to create horror show results, others work great?

### ISSUE THREAD

**Issue by MiloMindbender** [AliaksandrSiarohin/first-order-model#314]
Great piece of work.  I noticed something odd I wonder if you can explain.  All of the driving videos I have shot of myself seem to work great, however when I tried some from the internet I got horror show results and I'm wondering why.

I tried one scarlett johansson interview which was in black and white, caused really badly distorted output.  Thought it might have been because it was in black and white so tried a Charlez Theron interview and the same thing happened.  Not a single frame of good output.  Not sure what is different about these videos except that they do have a few jump-cut edits in them, would that cause problems?

I also tried a clip of John Oliver from "last week tonight" he speaks in a very animated way but the output had very small mouth movements like he was mumbling....maybe his glasses confused the algorithm.

Out of 4 clips I tried, only one got a good result, but nothing was as good as the driving videos I shot myself and I can't figure out why.  Is there something I'm missing?

I can send links to these videos if that would be helpful.

**Comment by AliaksandrSiarohin** [comment]
Send the videos

**Comment by MiloMindbender** [comment]
Here are some files.....
oliverkirk was the result of applying the john oliver clip to a picture of captain kirk.  This was the only driving clip that didn't produce a complete horror show, but as you can see his mouth never really opens up like it should.

The other two interview clips produced complete horrors, melting faces and such....not sure why.

[videos.zip](https://github.com/AliaksandrSiarohin/first-order-model/files/5441897/videos.zip)

**Comment by AliaksandrSiarohin** [comment]
First and second interview does not contain any face in the first frame, which is not supported. Use ```crop_video.py``` first.
Oliver is not alligned with the source, e.g it starts with open mouth. Try to use ```--select_best_frame```, or select frame with closed mouth using ```--best_frame``` argument..

**Comment by MiloMindbender** [comment]
Ah, ok I see.  I thought I had trimmed those files so they started on a face, I must have made an error somewhere along the line and not noticed it.  I'll go back and retry.  Thanks for the tip about aligning the source with the destination, that probably explains why some of the driven face photos worked better than others.  I'll retry and let you know.

**Comment by MiloMindbender** [comment]
Fixing the clips to start on a closed mouth frame fixed most of the issues, thanks!

Is it correct to assume you get the best results if the source and driving video are aligned as close as possible in terms of size, facial expression and starting position in the frame?

regarding --select_best_frame, my version only has the option --find_best_frame but that gives me this error: 

> ModuleNotFoundError: No module named 'face_alignment' 


which does not seem to be in your Github.  Where can I get it?

Full error text is below.

> python demo.py  --config config/vox-256.yaml --driving_video DrivingVideo/ScarletteTrim.mp4 --source_image p11.png --checkpoint vox-cpk.pth.tar --relative --adapt_scale --find_best_frame
> demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   config = yaml.load(f)
> Traceback (most recent call last):
>   File "demo.py", line 147, in <module>
>     i = opt.best_frame if opt.best_frame is not None else find_best_frame(source_image, driving_video, cpu=opt.cpu)
>   File "demo.py", line 81, in find_best_frame
>     import face_alignment
> ModuleNotFoundError: No module named 'face_alignment'

**Comment by AliaksandrSiarohin** [comment]
Yes beeter the allignment better result, you can read Reame animation demo section.

**Comment by MiloMindbender** [comment]
I think this covered the problem with my original question, so I'll close out the issue.
