### ISSUE TITLE
video is slow and very short

### ISSUE THREAD

**Issue by molo32** [AliaksandrSiarohin/first-order-model#32]
I'm generating facial animation in colab
  the obama video driving look very slow compared to the original 8s
I also used a 1 minute video driving and only generated a <30 second video.
how to increase the speed and the video time

**Comment by AliaksandrSiarohin** [comment]
The video is generated frame-by-frame, and saved at fps=30. You can set the desired fps when you store your video, ```imageio.mimsave(..., fps=60)```

**Comment by budidino** [comment]
Adding the `fps `parameter solved the issue with the exported video being more than 3x longer than the source. Thank you!
