### ISSUE TITLE
The difference between taichi-256.yaml and taichi-256-adv.yaml

### ISSUE THREAD

**Issue by JialeTao** [AliaksandrSiarohin/first-order-model#322]
Hi, noted that there are two settings on taichi and vox dataset. With no adversarial loss in config file tachi-256.yaml and vox-256.yaml, while with that in config file taichi-256-adv.yaml and vox-256-adv.yaml. So which one is better? Is the paper performance produced by non-adv or adv?

**Comment by AliaksandrSiarohin** [comment]
By non-adv, there is no visible difference in my opinion.

**Comment by JialeTao** [comment]
> By non-adv, there is no visible difference in my opinion.

Got it, thanks.
