### ISSUE TITLE
cropping video for fashion dataset

### ISSUE THREAD

**Issue by guptasg1997** [AliaksandrSiarohin/first-order-model#324]
how to crop video for fashion dataset?

**Comment by AliaksandrSiarohin** [comment]
It is already cropped.

**Comment by guptasg1997** [comment]
No, I mean to say that i need to implement this model for copying complete body motion (so i am using pretrained checkpoint of fashion dataset. Now before feeding my driving video, can i crop using face_allignment code or i need to crop using some other method

**Comment by guptasg1997** [comment]
@AliaksandrSiarohin , I mean to say that i need to implement this model for copying complete body motion (so i am using pretrained checkpoint of fashion dataset. Now before feeding my driving video, can i crop using face_allignment code or i need to crop using some other method

**Comment by AliaksandrSiarohin** [comment]
It generalize poorly on the fashion data, so most likely this will be useless for you. But you can try to adapt openpose or maskrcnn for this.
