### ISSUE TITLE
Question on demo

### ISSUE THREAD

**Issue by JimZeeKing** [AliaksandrSiarohin/first-order-model#333]
Hi, first off all thank you for this neat project!
I just want to know if the existing checkpoints can be use to drive a different video? Or must i start training specifically for my video? 
If no, what can i test with the demo, except for the examples showed on the github page?

I am trying to drive this image : 
![walking](https://user-images.githubusercontent.com/19315887/100006474-8aaffb80-2d98-11eb-8264-9981148b7172.png)
with this gif:
![walk](https://user-images.githubusercontent.com/19315887/100006494-93083680-2d98-11eb-8d98-fc21e791ef5e.gif)

Thank you

**Comment by AliaksandrSiarohin** [comment]
It works for the videos of the same object class. E.g. If model is trained in faces it will work only on faces. If model if trained on cartoon animals it will only work on similar cartoon animals. So you can use different video but it should have the same class as checkpoint. To animate stickmans you will need to train on a dataset of stickmans.

**Comment by JimZeeKing** [comment]
@AliaksandrSiarohin Thank you for the quick response!
