### ISSUE TITLE
about taichi training process

### ISSUE THREAD

**Issue by evinatgk** [AliaksandrSiarohin/first-order-model#340]
Hello. I have downloaded taichi dataset by following the instructions data/taichi-loading with .mp4 format. I have now 2 folders in path data/taichi-loading/taichi/ ..one is train and the other one is test.  train folder contains  1073 .mp4 format videos and test 87.... There were some broken links ,so the number of .mp4 videos are decreased. 
Then, I run  CUDA_VISIBLE_DEVICES=0,1,2,3 python run.py --config config/taichi-adv-256.yaml --device_ids 0,1,2,3
and I get this output:

/anaconda3/envs/evinata/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
run.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "run.py", line 72, in <module>
    dataset = FramesDataset(is_train=(opt.mode == 'train'), **config['dataset_params'])
  File "/home/vtagka/animation/frames_dataset.py", line 66, in __init__
    self.videos = os.listdir(root_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'data/taichi-png'

what is taichi-png folder? I have to create it? Also, where are the source images located? Should I add them by my own? 
Thanks!

**Comment by AliaksandrSiarohin** [comment]
So you should specify the path where is your dataset in yaml file. Source and driving images are randomly sample from the same video.

**Comment by evinatgk** [comment]
Thank you very much!
