### ISSUE TITLE
Colab Error : fd 78 failed with Input/output error

### ISSUE THREAD

**Issue by AhmedKchaou91** [AliaksandrSiarohin/first-order-model#349]
Hello,

I tried using your google collab and i got this error on "Create a model and load checkpoints" step
note that i used the default configuration (default video and default image).

`RuntimeError                              Traceback (most recent call last)

<ipython-input-45-dbd18151b569> in <module>()
      1 from demo import load_checkpoints
      2 generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
----> 3                             checkpoint_path='/content/gdrive/My Drive/first-order-motion-model/vox-cpk.pth.tar')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    779     offset = f.tell() if f_should_read_directly else None
    780     for key in deserialized_storage_keys:
--> 781         assert key in deserialized_objects
    782         deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
    783         if offset is not None:

RuntimeError: read(): fd 78 failed with Input/output error`

**Comment by AliaksandrSiarohin** [comment]
Something wring with the checkpoint how did you put it to Google drive. What is the size of it?

**Comment by AhmedKchaou91** [comment]
Fixed.

I just removed the shortcut of "first-order-motion-model" folder from my drive and then created another shortcut of this same folder and it works now. thank you for your help.

Note that I used this collab 3 months ago and it worked.  if anyone get this error just remove and re-assign the folder.
