### ISSUE TITLE
What does each value mean in log.txt?

### ISSUE THREAD

**Issue by chloejihye** [AliaksandrSiarohin/first-order-model#356]
Hello! First of all, thank you so much for sharing this. I'm really impressed with the great work!

I'm training my own dataset and would like to ask some questions about the log.txt.

For each epoch, I could check the loss value in log.txt, but would like to know what specifically each value means? (`perceptual`, `equivariance_value`, `equivariance_jacobian`) I was trying to search for the concept but no luck so far! 

Though it would be hard to understand the core of overall algorithms, it would be very helpful for me to understand the basic concept of each value. Thank you!

`log.txt`
00000099) perceptual - 119.43776; equivariance_value - 0.16928; equivariance_jacobian - 0.38989
00000100) perceptual - 115.52567; equivariance_value - 0.16336; equivariance_jacobian - 0.38148
00000101) perceptual - 114.48615; equivariance_value - 0.16161; equivariance_jacobian - 0.38326
00000102) perceptual - 113.62000; equivariance_value - 0.15871; equivariance_jacobian - 0.37829
00000103) perceptual - 111.52644; equivariance_value - 0.16194; equivariance_jacobian - 0.38003
00000104) perceptual - 111.16970; equivariance_value - 0.15887; equivariance_jacobian - 0.38029
00000105) perceptual - 111.75166; equivariance_value - 0.15967; equivariance_jacobian - 0.38152
00000106) perceptual - 109.65020; equivariance_value - 0.16150; equivariance_jacobian - 0.38408
00000107) perceptual - 109.27444; equivariance_value - 0.15851; equivariance_jacobian - 0.38062
00000108) perceptual - 108.66588; equivariance_value - 0.15721; equivariance_jacobian - 0.37647
00000109) perceptual - 108.77213; equivariance_value - 0.15622; equivariance_jacobian - 0.37676
00000110) perceptual - 107.21622; equivariance_value - 0.15992; equivariance_jacobian - 0.38098
00000111) perceptual - 106.52648; equivariance_value - 0.15731; equivariance_jacobian - 0.38008
00000112) perceptual - 107.00948; equivariance_value - 0.15343; equivariance_jacobian - 0.37506
00000113) perceptual - 106.63305; equivariance_value - 0.15905; equivariance_jacobian - 0.38243
00000114) perceptual - 106.31609; equivariance_value - 0.15523; equivariance_jacobian - 0.38156
00000115) perceptual - 107.03062; equivariance_value - 0.15672; equivariance_jacobian - 0.38427
00000116) perceptual - 106.41008; equivariance_value - 0.15520; equivariance_jacobian - 0.38132
00000117) perceptual - 105.37106; equivariance_value - 0.15438; equivariance_jacobian - 0.37861
00000118) perceptual - 105.85702; equivariance_value - 0.15369; equivariance_jacobian - 0.37725
00000119) perceptual - 105.43564; equivariance_value - 0.15567; equivariance_jacobian - 0.37770

**Comment by AliaksandrSiarohin** [comment]
You should read the paper, perceptual is a reconstruction loss equivariance_value is equivariance loss for keypoints same for equivariance_jacobian.

**Comment by chloejihye** [comment]
@AliaksandrSiarohin Thank you so much!

**Comment by chloejihye** [comment]
-
