### ISSUE TITLE
headswap

### ISSUE THREAD

**Issue by CarolinGao** [AliaksandrSiarohin/first-order-model#36]
The current method is limited to giving a head driving video and head image. Any  suggestions that if I  just provide a head image and a driving video like a lecture video, and I want to replace the people head in the video with a head image？

**Comment by AliaksandrSiarohin** [comment]
I don't really get what you mean. What lecture video you meant?

**Comment by ghost** [comment]
@AliaksandrSiarohin I think it is the face swapping application of the paper

**Comment by AliaksandrSiarohin** [comment]
https://github.com/AliaksandrSiarohin/motion-cosegmentation
```
python part_swap.py --source_image ... --target_video ... --checkpoint vox-first-order.pth.tar --config config/vox-256-10segments.yaml --supervised --first_order_motion_model
```

**Comment by kenny1323** [comment]
This is just an idea.
step1: you have the  video video1.mp4 and an image img1.jpg 
inside the video1.mp4 there is head1;
inside the img1.jpg there is head2;

step1: use a software to animate img1,jpg and get a video (e.g. myheritage deep nostalgia);
now you have the video img1_animated.mp4 from the single image img1,jpg;

step2: use a library to swap the heads of the videos img_video.mp4 and   video1.mp4


More.
1. about the image animation, search on github image animation python
https://github.com/topics/image-animation


2. About heads swaps try this:
https://github.com/michaildoukas/head2head
