### ISSUE TITLE
Where can I contact you?

### ISSUE THREAD

**Issue by eSaniello** [AliaksandrSiarohin/first-order-model#37]
Hi, sorry leaving this here but where can I contact the developer. I have some questions that might not be very appropriate to be in a github issue. Please leave an email or some sort of social media contact here so I can contact you. Very nice project btw. Love it. Thanks.

**Comment by AliaksandrSiarohin** [comment]
Emails of all the authors provided in the paper as usual. My email is: aliaksandr.siarohin@unitn.it

**Comment by eSaniello** [comment]
Sorry I missed it then haha. Thanks. I'll contact you.
