### ISSUE TITLE
Regarding Tai-chi dataset license

### ISSUE THREAD

**Issue by Adithya-MN** [AliaksandrSiarohin/first-order-model#376]
Firstly, I'd like to thank the authors for sharing the code and data publicly. 

I had a question regarding the Tai-Chi HD dataset - I noticed that while the paper mentions the dataset is shared publicly, I could not find a mention of the license it is shared under in the paper and the repositories . Could you please help me with the same?

**Comment by AliaksandrSiarohin** [comment]
The dataset is downloaded from YouTube, so for each sample corresponding YouTube licence will apply. To this end we shared only the annotations, e.g. Taichi-Metadata.

**Comment by Adithya-MN** [comment]
Thanks for the quick clarification!  :)

**Comment by Adithya-MN** [comment]
Looking at other datasets with similar origin (Youtube), they seem to have an overall license for the dataset (e.g. VoxCeleb - [https://www.robots.ox.ac.uk/~vgg/data/voxceleb/files/license.txt](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/files/license.txt)
Would there be anything similar for TaiChi HD? This information would really help!

**Comment by AliaksandrSiarohin** [comment]
For vox celeb license is only related to annotations. Videos is not covered.

**Comment by Adithya-MN** [comment]
So would there be a similar license for the TaiChi annotations?

**Comment by Adithya-MN** [comment]
Just a gentle reminder.. Kindly let me know regarding this when possible - any sort of license information on annotations would be really useful for people working on further research on this dataset and MonkeyNet/FOMM (with regards to dataset approval)

**Comment by AliaksandrSiarohin** [comment]
I guess it will be the same as the license of vox annotations.

**Comment by Adithya-MN** [comment]
Thanks for the clarification!
