### ISSUE TITLE
DataLoader worker (pid 1237) is killed by signal: Killed.

### ISSUE THREAD

**Issue by ritikarp** [AliaksandrSiarohin/first-order-model#385]
### Trying to train on my own dataset using collab. Getting this error below:

Use predefined train-test split.
Training...
  0% 0/10 [00:00<?, ?it/s]tcmalloc: large alloc 2309472256 bytes == 0x5654ccf58000 @  0x7fc2707401e7 0x7fc26d1cc46e 0x7fc26d21cc7b 0x7fc26d21cd18 0x7fc26d2d8d79 0x7fc26d2dbe4c 0x7fc26d3fae7f 0x7fc26d400fb5 0x7fc26d402e3d 0x7fc26d404516 0x56543fdb08e9 0x56543fe24ade 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1ee0d 0x56543fdb177a 0x56543fe2086a 0x56543fe1ee0d 0x56543fdb38be 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59 0x56543fe1ffad 0x56543fdb372b 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59
tcmalloc: large alloc 2309472256 bytes == 0x5654ccf58000 @  0x7fc2707401e7 0x7fc26d1cc46e 0x7fc26d21cc7b 0x7fc26d21cd18 0x7fc26d2d8d79 0x7fc26d2dbe4c 0x7fc26d3fae7f 0x7fc26d400fb5 0x7fc26d402e3d 0x7fc26d404516 0x56543fdb08e9 0x56543fe24ade 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1ee0d 0x56543fdb177a 0x56543fe2086a 0x56543fe1ee0d 0x56543fdb38be 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59 0x56543fe1ffad 0x56543fdb372b 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59
tcmalloc: large alloc 2309472256 bytes == 0x5654ccf58000 @  0x7fc2707401e7 0x7fc26d1cc46e 0x7fc26d21cc7b 0x7fc26d21cd18 0x7fc26d2d8d79 0x7fc26d2dbe4c 0x7fc26d3fae7f 0x7fc26d400fb5 0x7fc26d402e3d 0x7fc26d404516 0x56543fdb08e9 0x56543fe24ade 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1ee0d 0x56543fdb177a 0x56543fe2086a 0x56543fe1ee0d 0x56543fdb38be 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59 0x56543fe1ffad 0x56543fdb372b 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59
tcmalloc: large alloc 2309472256 bytes == 0x5654ccf58000 @  0x7fc2707401e7 0x7fc26d1cc46e 0x7fc26d21cc7b 0x7fc26d21cd18 0x7fc26d2d8d79 0x7fc26d2dbe4c 0x7fc26d3fae7f 0x7fc26d400fb5 0x7fc26d402e3d 0x7fc26d404516 0x56543fdb08e9 0x56543fe24ade 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1ee0d 0x56543fdb177a 0x56543fe2086a 0x56543fe1ee0d 0x56543fdb38be 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59 0x56543fe1ffad 0x56543fdb372b 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59
tcmalloc: large alloc 2309472256 bytes == 0x5654ccf58000 @  0x7fc2707401e7 0x7fc26d1cc46e 0x7fc26d21cc7b 0x7fc26d21cd18 0x7fc26d2d8d79 0x7fc26d2dbe4c 0x7fc26d3fae7f 0x7fc26d400fb5 0x7fc26d402e3d 0x7fc26d404516 0x56543fdb08e9 0x56543fe24ade 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1ee0d 0x56543fdb177a 0x56543fe2086a 0x56543fe1ee0d 0x56543fdb38be 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59 0x56543fe1ffad 0x56543fdb372b 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59
tcmalloc: large alloc 2309472256 bytes == 0x5654ccf58000 @  0x7fc2707401e7 0x7fc26d1cc46e 0x7fc26d21cc7b 0x7fc26d21cd18 0x7fc26d2d8d79 0x7fc26d2dbe4c 0x7fc26d3fae7f 0x7fc26d400fb5 0x7fc26d402e3d 0x7fc26d404516 0x56543fdb08e9 0x56543fe24ade 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1eb0e 0x56543fdb177a 0x56543fe1fa45 0x56543fe1ee0d 0x56543fdb177a 0x56543fe2086a 0x56543fe1ee0d 0x56543fdb38be 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59 0x56543fe1ffad 0x56543fdb372b 0x56543fdf45e9 0x56543fdf455c 0x56543fe97e59
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1237) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset)
  File "/content/first-order-model/train.py", line 50, in train
    for x in dataloader:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1237) exited unexpectedly
  0% 0/10 [00:24<?, ?it/s]

#### Need help with this.

**Comment by AliaksandrSiarohin** [comment]
How did you modify the code?

**Comment by ritikarp** [comment]
First I created my dataset and config file as mentioned in readme.md
then i got the assertion error for device, so i removed device. 
next memtest=false added
then i got this error.

**Comment by AliaksandrSiarohin** [comment]
There are some problems with your videos. Maybe they are too large.

**Comment by ritikarp** [comment]
yes, understood the problem. What should do to create my dataset from a recorded video? Should I upload it on youtube and trim it or earlier I trimmed it using some software which gave error.
