### ISSUE TITLE
How to get this file dataset_name.yaml and where can I download it ?

### ISSUE THREAD

**Issue by iamchenxin-coder** [AliaksandrSiarohin/first-order-model#389]
Hello，I want to know where to get this file or how to create it. In addition, this project supports the input of **a static image and an audio segment**, so as to generate a video of a **person's lip movement** according to the content of the audio

**Comment by AliaksandrSiarohin** [comment]
dataset_name.yaml is one of vox-256.yaml or taich-256.yaml or other, for faces use vox-256.yaml. No it is not supported.

**Comment by iamchenxin-coder** [comment]
Thanks a lot
