### ISSUE TITLE
Fail pip install

### ISSUE THREAD

**Issue by francesco086** [AliaksandrSiarohin/first-order-model#396]
I created a venv with python 3.8.6 on Mac Os 10.15.7 and run `pip install -r requirements.txt`.
I got this message error:
```
ERROR: Could not find a version that satisfies the requirement PyWavelets==0.5.2
ERROR: No matching distribution found for PyWavelets==0.5.2
```
I believe that the problem is caused by the fact that `PyWavelets==0.5.2` is very old (2017!) and the author did not make it compatible with python 3.8.
I tried with python 3.7.7 and it worked. I would therefore suggest to add in the README this information.

I created a pull request for you: https://github.com/AliaksandrSiarohin/first-order-model/pull/395

**Comment by AliaksandrSiarohin** [comment]
Probably it is better just remove it from requirements.

**Comment by dylan-cm** [comment]
the change to requirements.txt i made to get it to work 
note: i am still having issues with running the demo on cuda
```
imageio==2.3.0
matplotlib==3.3.4
numpy==1.20.0
pandas==1.2
python-dateutil==2.7.3
pytz==2018.5
PyYAML==5.4
scikit-image==0.18.0
scikit-learn==0.24.0 
scipy==1.6.2 
torch==1.8.1
torchvision==0.2.1
tqdm==4.24.0
```

**Comment by foreverabhi2002** [comment]
This will definitely run try this :-

imageio==2.9.0
matplotlib==3.4.1
numpy==1.19.5
pandas==1.2.3
python-dateutil==2.7.3
pytz==2021.1
PyYAML==5.4.1
scikit-image==0.18.1
scikit-learn==0.24.1
scipy==1.6.2
torch==1.8.1
torchvision==0.9.1
tqdm==4.24.0

**Comment by Soorya-S** [comment]
> the change to requirements.txt i made to get it to work
> note: i am still having issues with running the demo on cuda
> 
> ```
> imageio==2.3.0
> matplotlib==3.3.4
> numpy==1.20.0
> pandas==1.2
> python-dateutil==2.7.3
> pytz==2018.5
> PyYAML==5.4
> scikit-image==0.18.0
> scikit-learn==0.24.0 
> scipy==1.6.2 
> torch==1.8.1
> torchvision==0.2.1
> tqdm==4.24.0
> ```

running this command solved the CUDA error. Now I'm able to run the code using CUDA. But I don't know how to embed this inside the requirements.txt file ( I'm a python noob)
pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102  -f https://download.pytorch.org/whl/torch_stable.html

**Comment by hamzanaeem1999** [comment]
> > the change to requirements.txt i made to get it to work
> > note: i am still having issues with running the demo on cuda
> > ```
> > imageio==2.3.0
> > matplotlib==3.3.4
> > numpy==1.20.0
> > pandas==1.2
> > python-dateutil==2.7.3
> > pytz==2018.5
> > PyYAML==5.4
> > scikit-image==0.18.0
> > scikit-learn==0.24.0 
> > scipy==1.6.2 
> > torch==1.8.1
> > torchvision==0.2.1
> > tqdm==4.24.0
> > ```
> 
> running this command solved the CUDA error. Now I'm able to run the code using CUDA. But I don't know how to embed this inside the requirements.txt file ( I'm a python noob)
> pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 -f https://download.pytorch.org/whl/torch_stable.html

Worked Thanks !
