### ISSUE TITLE
Question about Reconstruction loss

### ISSUE THREAD

**Issue by yoyo-nb** [AliaksandrSiarohin/first-order-model#401]
Thank you for your excellent work!
I downloaded the models `vox-adv-cpk.pth.tar` and `vox-cpk.pth.tar`, and then used [video preprocessing](https://github.com/AliaksandrSiarohin/video-preprocessing) to download the dataset `VoxCeleb1`. The total size of the dataset is 306GB, and a small number of video URLs are invalid, so I cannot get the complete dataset. When I calculated the L1 loss mentioned in the paper, I used the command:
```shell
python run.py --config config/vox-adv-256.yaml --mode reconstruction --checkpoint vox-adv-cpk.pth.tar
```
and
```shell
python run.py --config config/vox-256.yaml --mode reconstruction --checkpoint vox-cpk.pth.tar
```
The results obtained are:
```
Reconstruction loss: 0.045256987
```
and
```
Reconstruction loss: 0.045593876
```
This is different from the 0.043 mentioned in the paper.
Is this caused by a small amount of missing data in my dataset?

**Comment by yoyo-nb** [comment]
The size of test folder is 11GB.

**Comment by AliaksandrSiarohin** [comment]
Probably.

**Comment by yoyo-nb** [comment]
I downloaded the TaiChi dataset and there are some URLs invalid too. I want to use the same dataset in the paper. Do you have unprocessed video files of the Vox1 and taichi datasets? There are the [video_ids](https://gist.github.com/yoyo-nb/be603efb5cad81d143f81095fcf23794) that I failed to download (Vox1 176 URLs and TaiChi 13 URLs). Could you send these videos to me by email? My email is zhaojian2116@foxmail.com. Thank you very much!

**Comment by AliaksandrSiarohin** [comment]
I don't have unprocessed videos anymore.

**Comment by yoyo-nb** [comment]
Okay, thank you for your reply.
