### ISSUE TITLE
align images is missing?

### ISSUE THREAD

**Issue by aelizie** [AliaksandrSiarohin/first-order-model#406]
I'm trying to run the collab at https://colab.research.google.com/github/tg-bomze/Face-Image-Motion-Model/blob/master/Face_Image_Motion_Model_(Photo_2_Video)_Eng.ipynb#scrollTo=cdO_RxQZLahB
but that gives an error during pulling for align.zip?

Cloning into 'first_order_model'...
remote: Enumerating objects: 259, done.
remote: Total 259 (delta 0), reused 0 (delta 0), pack-reused 259
Receiving objects: 100% (259/259), 72.13 MiB | 32.00 MiB/s, done.
Resolving deltas: 100% (131/131), done.
/content/first_order_model
curl: (7) Failed to connect to srv-file22.gofile.io port 443: Connection refused
--2021-04-11 22:30:33--  https://srv-file22.gofile.io/download/SUyfwc/vox-cpk.pth.tar
Resolving srv-file22.gofile.io (srv-file22.gofile.io)... 5.9.77.62
Connecting to srv-file22.gofile.io (srv-file22.gofile.io)|5.9.77.62|:443... failed: Connection refused.
--2021-04-11 22:30:33--  https://srv-file22.gofile.io/download/SUyfwc/shape_predictor_68_face_landmarks.dat.bz2
Resolving srv-file22.gofile.io (srv-file22.gofile.io)... 5.9.77.62
Connecting to srv-file22.gofile.io (srv-file22.gofile.io)|5.9.77.62|:443... failed: Connection refused.
--2021-04-11 22:30:33--  https://srv-file22.gofile.io/download/SUyfwc/align.zip
Resolving srv-file22.gofile.io (srv-file22.gofile.io)... 5.9.77.62
Connecting to srv-file22.gofile.io (srv-file22.gofile.io)|5.9.77.62|:443... failed: Connection refused.
Archive:  align.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of align.zip or
        align.zip.zip, and cannot find align.zip.ZIP, period.

**Comment by AliaksandrSiarohin** [comment]
I'm not the author of that notebook, post this issue in the related repository.
