### ISSUE TITLE
Suggestion on the Google Colab Demo

### ISSUE THREAD

**Issue by graphemecluster** [AliaksandrSiarohin/first-order-model#407]
I suggest that the demo should be more user-friendly:
- **Don't use Google Drive.** The program will copy all the things from the user's drive. That is, the user has to wait until all 200GB contents got copied if the user's drive has 200GB contents. Use a simple **file picker** instead.
- `HTML(display(source_image, ……` simply waste time. Actually if you really need this you just need a line of FFmpeg. But why don't you just make two UI components side by side???
- It will be even better to add back the original audio to the generated video by providing only one line of FFmpeg command.

[Here is a sample](https://colab.research.google.com/drive/1PSmW3pRdEK75pnx3M7QRBlZLTExgWDIS?usp=sharing) by me, original made for the meme, with a default `original.mp4`.
Just add one more button for uploading video and a drop-down list for choosing model and that's it!

**Comment by AliaksandrSiarohin** [comment]
Thank you for your suggestion, please can make a pool request.

**Comment by graphemecluster** [comment]
OK, I will open a pull request later.
