### ISSUE TITLE
warning- conversion float32 to uint8

### ISSUE THREAD

**Issue by Kubakowal** [AliaksandrSiarohin/first-order-model#41]
Hi, program complie but I got this warnings:
WARNING:root:Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
A lot of them. Waht am I doing wrong?

**Comment by teebu** [comment]
Add: 
```
from skimage import img_as_ubyte
```

To fix it, change the last line in demo.py to:

```
imageio.mimsave(opt.result_video, [img_as_ubyte(frame) for frame in predictions], fps=fps)
```

**Comment by Kubakowal** [comment]
Thanks, it worked.

**Comment by teebu** [comment]
If you don't want to see the other warnings, add

```
import warnings
warnings.filterwarnings("ignore")
```
