### ISSUE TITLE
Question about backward warping implementation

### ISSUE THREAD

**Issue by zzh-tech** [AliaksandrSiarohin/first-order-model#418]
Hi, thanks for your interesting work!
I have a question about [your implementation of backward warping](https://github.com/AliaksandrSiarohin/first-order-model/blob/31628f83235c5b6307bb1ae34c7c4c02ac3a5886/modules/generator.py#L55).
[In the case where the size of the source image and the flow field is different](https://github.com/AliaksandrSiarohin/first-order-model/blob/31628f83235c5b6307bb1ae34c7c4c02ac3a5886/modules/generator.py#L86), shouldn't we multiply the size ratio to the original flow field?

**Comment by AliaksandrSiarohin** [comment]
It is not my implementation, it is pytorch implementation. It is assumed that values is always in range [-1,1]. Pytorch account for different resolution inside grid_sample.

**Comment by zzh-tech** [comment]
I got it.
Thanks :)
