### ISSUE TITLE
Questions about ColorJitter for PIL.image 

### ISSUE THREAD

**Issue by Cold-Winter** [AliaksandrSiarohin/first-order-model#419]
Hi,

When i am checking the augmentation code.

I find that color jitters for numpy array and PIL.image are different.
Can you please help me check this line:
https://github.com/AliaksandrSiarohin/first-order-model/blob/master/augmentation.py#L314

I suppose this is not correct since for every PIL.image, it will only apply the last transformation in img_transforms

**Comment by AliaksandrSiarohin** [comment]
Since it is never used for pil images it is likely, that I only change the np.array part.
