### ISSUE TITLE
Older one was better than the Newer one

### ISSUE THREAD

**Issue by afasgasasrga** [AliaksandrSiarohin/first-order-model#422]
Hey can you bring back the older demo? the newer demo wont let me make the deepfake

i know this isnt colab but pls just make other web and bring back the older demo

**Comment by AliaksandrSiarohin** [comment]
It is in old_demo.ipynb

**Comment by AliaksandrSiarohin** [comment]
I see the problem. I will fix it.

**Comment by AliaksandrSiarohin** [comment]
Now you should see old colab when you press open in colab button (inside old_demo.py).
