### ISSUE TITLE
Can't upload source movement file

### ISSUE THREAD

**Issue by clareh123** [AliaksandrSiarohin/first-order-model#424]
I'm struggling to upload a source file to the first order model demo.  Does it need to be a specific format?

**Comment by AliaksandrSiarohin** [comment]
Which format are you using?

**Comment by clareh123** [comment]
I've tried .MOV and also converting it to .mp4 but neither seem to work

**Comment by AliaksandrSiarohin** [comment]
@clareh123 can you post your source and driving?
@graphemecluster can you investigate this issue please?

**Comment by clareh123** [comment]
I just tried to post the file here but it says it's too big.  Perhaps that's the issue?  And sorry you'll have to excuse my lack of tech awareness but what do you mean by "driving"?

**Comment by graphemecluster** [comment]
You could temporarily use [this forked one](https://colab.research.google.com/github/graphemecluster/first-order-model/blob/master/demo.ipynb) until it is merged.
