### ISSUE TITLE
Unable to use personal videos on latest demo. OSError: Could not load meta information

### ISSUE THREAD

**Issue by jesshew** [AliaksandrSiarohin/first-order-model#425]
Hello, I was trying to run your new demo with my own videos but got the following error :

OSError: Could not load meta information=== stderr ===ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared  libavutil      55. 78.100 / 55. 78.100  libavcodec     57.107.100 / 57.107.100  libavformat    57. 83.100 / 57. 83.100  libavdevice    57. 10.100 / 57. 10.100  libavfilter     6.107.100 /  6.107.100  libavresample   3.  7.  0 /  3.  7.  0  libswscale      4.  8.100 /  4.  8.100  libswresample   2.  9.100 /  2.  9.100  libpostproc    54.  7.100 / 54.  7.100/tmp/imageio_nqlhweq8: Invalid data found when processing input site:stackoverflow.com

The videos that I used can be found in this google drive:
https://drive.google.com/drive/folders/1v2dAoiOd-oaQ3vtSjnbowaiZY2-pim7L?usp=sharing

FYI, They're all in the correct format and size as I have squared them already.  I can upload the videos, and run, but it won't generate an output. Also, I tried using the same videos on your old demo and it works fine. is there a bug in the [latest demo](https://colab.research.google.com/github/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb#scrollTo=Oxi6-riLOgnm) ?

**Comment by AliaksandrSiarohin** [comment]
@graphemecluster?

**Comment by UnderxPipe1985** [comment]
I have the exact same issue. It works with the videos provided in the demo, but with uploaded videos doesn't work and it gives me this error.

**Comment by graphemecluster** [comment]
You could temporarily use [this forked one](https://colab.research.google.com/github/graphemecluster/first-order-model/blob/master/demo.ipynb) until it is merged.
