### ISSUE TITLE
Is it possible to adjust face plasticity? 

### ISSUE THREAD

**Issue by ghost** [AliaksandrSiarohin/first-order-model#428]
I was trying to compare two models, fsgan Face Reenactment and first-order-motion-model (absolute coordinates): https://youtu.be/v0K1NDsQY_0?t=59
Around this timestamp (0:59) the animated character on the right (fsgan) makes an eyebrow movement, but in the left video the eyebrow movement is not noticeable. I've noticed also that facial expressions from the driving video are transferred in a less pronounced way (as if the face muscles of the target character were less movable). Is there a way to adjust some parameters to increase plasticity of the face, or would it require to retrain the model on my own datasets (for example, which specifically contain separate eyebrow movements)?

**Comment by AliaksandrSiarohin** [comment]
You could try to increase number of keypoints. Fsgan use 68 kp, while fomm use 10.

**Comment by AliaksandrSiarohin** [comment]
You could try to increase number of keypoints. Fsgan use 68 kp, while fomm use 10.

**Comment by Sentero-esp12** [comment]
Thank you, I tried it (setting `num_kp: 50` in vox-adv-256.yaml), but getting this error:
```
Traceback (most recent call last):
  File "demo.py", line 146, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 44, in load_checkpoints
    generator.load_state_dict(checkpoint['generator'])
  File "/home/user1/miniconda3/envs/first/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for OcclusionAwareGenerator:
	size mismatch for dense_motion_network.hourglass.encoder.down_blocks.0.conv.weight: copying a param with shape torch.Size([128, 44, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 204, 3, 3]).
	size mismatch for dense_motion_network.mask.weight: copying a param with shape torch.Size([11, 108, 7, 7]) from checkpoint, the shape in current model is torch.Size([51, 268, 7, 7]).
	size mismatch for dense_motion_network.mask.bias: copying a param with shape torch.Size([11]) from checkpoint, the shape in current model is torch.Size([51]).
	size mismatch for dense_motion_network.occlusion.weight: copying a param with shape torch.Size([1, 108, 7, 7]) from checkpoint, the shape in current model is torch.Size([1, 268, 7, 7]).
```
Should I change some other parameters?

**Comment by AliaksandrSiarohin** [comment]
It requires retraining.

**Comment by ghost** [comment]
Ok, got it, thank you
