### ISSUE TITLE
I've a doubt about face swapping.

### ISSUE THREAD

**Issue by ErikDz** [AliaksandrSiarohin/first-order-model#433]
When you say: "For both unsupervised and supervised video editing, such as face-swap, please refer to Motion Co-Segmentation. Training"

Does that mean that for face-swapping I need to use the motion-cosegmentation repo? Or do I need to do any modifications to it with the first-order-model's checkpoints?

Can you please explained in a dumb-downed way how to achieve the face-swap you have on your gif?

Many thanks.

**Comment by AliaksandrSiarohin** [comment]
Yes you need to use other repo.

**Comment by ErikDz** [comment]
Do I need to make any modifications to it?

**Comment by AliaksandrSiarohin** [comment]
No.

**Comment by ErikDz** [comment]
Okay! Many thanks man, really appreciate it. One last thing: which checkpoint should I use?

**Comment by AliaksandrSiarohin** [comment]
Same as fomm, read instructions on how to modify the command.
