### ISSUE TITLE
Sound doesn't downl

### ISSUE THREAD

**Issue by clareh123** [AliaksandrSiarohin/first-order-model#434]
Hi.  I've managed to get the video upload working but now when I download the file, the audio doesn't seem to download with it.  When I play it from my computer it says audio no available

![image](https://user-images.githubusercontent.com/84448881/120348648-46785780-c2f5-11eb-8d58-4be364047f6b.png)

**Comment by ghost** [comment]
I think it doesn't include audio by default (but perhaps there is a way to do it). You should add the audio back manually via some video editor
