### ISSUE TITLE
Training your own dataset ....

### ISSUE THREAD

**Issue by eastchun** [AliaksandrSiarohin/first-order-model#435]
To train my own dataset, you mentioned that :
   
     " for each video make a separate folder with all the frames in '.png' format.

Does this mean that I have to create  .png images for each ,mp4 video in train directory?  
FrameDataset appears to access only .mp4 videos in train directory (not .png images) ???

**Comment by AliaksandrSiarohin** [comment]
You have to create a folder with all png images for each mp4. It accept both, but mp4 will be slower.
