### ISSUE TITLE
Problem downloading taichi dataset

### ISSUE THREAD

**Issue by zhangyahu1** [AliaksandrSiarohin/first-order-model#439]
Thanks for your nice work!
I meet a problme when downloading taichi dataset:

```
python load_videos.py --metadata taichi-metadata.csv --format .mp4 --out_folder taichi --workers 6
/home/yzhang4/anaconda3/envs/motion/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/yzhang4/anaconda3/envs/motion/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
0it [00:00, ?it/s]Can not load video KYdyIdusD0g, broken link
18it [07:14, 17.29s/it]Can not load video ytT4iU7h-A8, broken link
21it [08:26, 21.01s/it]Can not load video JdiIQg47Wc4, broken link
32it [12:43, 15.10s/it]Can not load video PKE4yfDESa0, broken link
56it [20:29, 30.27s/it]Can not load video _XRyc2kiTlM, broken link
97it [44:29, 27.52s/it]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "load_videos.py", line 84, in run
    save(os.path.join(args.out_folder, partition, path), entry['frames'], args.format)
  File "load_videos.py", line 22, in save
    imageio.mimsave(path, frames)
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/site-packages/imageio/core/functions.py", line 347, in mimwrite
    raise RuntimeError('Zero images were written.')
RuntimeError: Zero images were written.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_videos.py", line 112, in <module>
    for chunks_data in tqdm(pool.imap_unordered(run, zip(video_ids, args_list))):
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/multiprocessing/pool.py", line 699, in next
    raise value
RuntimeError: Zero images were written.

```
I update the latest version of youtube-di by 'wget https://yt-dl.org/downloads/latest/youtube-dl -O youtube-dl', but it still doesn't work for me. Could you please give me some advice?

**Comment by KHao123** [comment]
I meet the same problem. How do you solve it?

**Comment by bajiua** [comment]
> 感谢您的出色工作！ 我在下载太极数据集时遇到问题：
> 
> ```
> python load_videos.py --metadata taichi-metadata.csv --format .mp4 --out_folder taichi --workers 6
> /home/yzhang4/anaconda3/envs/motion/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /home/yzhang4/anaconda3/envs/motion/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> 0it [00:00, ?it/s]Can not load video KYdyIdusD0g, broken link
> 18it [07:14, 17.29s/it]Can not load video ytT4iU7h-A8, broken link
> 21it [08:26, 21.01s/it]Can not load video JdiIQg47Wc4, broken link
> 32it [12:43, 15.10s/it]Can not load video PKE4yfDESa0, broken link
> 56it [20:29, 30.27s/it]Can not load video _XRyc2kiTlM, broken link
> 97it [44:29, 27.52s/it]
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "load_videos.py", line 84, in run
>     save(os.path.join(args.out_folder, partition, path), entry['frames'], args.format)
>   File "load_videos.py", line 22, in save
>     imageio.mimsave(path, frames)
>   File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/site-packages/imageio/core/functions.py", line 347, in mimwrite
>     raise RuntimeError('Zero images were written.')
> RuntimeError: Zero images were written.
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "load_videos.py", line 112, in <module>
>     for chunks_data in tqdm(pool.imap_unordered(run, zip(video_ids, args_list))):
>   File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
>     for obj in iterable:
>   File "/home/yzhang4/anaconda3/envs/motion/lib/python3.6/multiprocessing/pool.py", line 699, in next
>     raise value
> RuntimeError: Zero images were written.
> ```
> 
> [我通过“wget https://yt-dl.org/downloads/latest/youtube-dl](https://yt-dl.org/downloads/latest/youtube-dl) -O youtube-dl”更新了 youtube-di 的最新版本，但它仍然对我不起作用。您能给我一些建议吗？

Hello, have you solved this problem？

**Comment by bajiua** [comment]
> 我遇到了同样的问题。你如何解决它？

Hello, have you solved this problem？
