### ISSUE TITLE
execute demo.py with GPU

### ISSUE THREAD

**Issue by ElmiraNa** [AliaksandrSiarohin/first-order-model#448]
Hi everybody
I run this command in win10:
```set CUDA_VISIBLE_DEVICES=0 & python demo.py  --config config/dataset_name.yaml --driving_video path/to/driving --source_image path/to/source --checkpoint path/to/checkpoint --relative --adapt_scale```

but there is no difference in run time when I run it without setting Cuda. is it right?
and how can I run demo.py on gpu?

**Comment by AliaksandrSiarohin** [comment]
CUDA_VISIBLE_DEVICES=0 specify on which gou to run. So it expected that it make no difference if you have single gpu. You should check nvidia-smi to see if gpu is used.

**Comment by ElmiraNa** [comment]
thank you for your respond. I mean is demo.py can run on gpu with above command and is there no need to change the code of demo.py?

**Comment by AliaksandrSiarohin** [comment]
No.
