### ISSUE TITLE
About pre-trained checkpoint

### ISSUE THREAD

**Issue by yoyo-nb** [AliaksandrSiarohin/first-order-model#459]
When I tested with the pre-trained checkpoint, I found that the L1 distance of the VoxCeleb and taichiHD datasets was better than the L1 distance in the paper. I want to know why. 
Is the pre-trained checkpoint trained on the training set or on the entire dataset (including training set and testing set).
Thank you.

**Comment by AliaksandrSiarohin** [comment]
Provided checkpoints obtained with more iterations. In paper number of iterations is chosen to be comparable with the baselines.

**Comment by yoyo-nb** [comment]
thank you!
