### ISSUE TITLE
Loss values during training

### ISSUE THREAD

**Issue by onzone** [AliaksandrSiarohin/first-order-model#460]
Thank you for the awesome work. I am currently training the FOMM model with 20 keypoints. Can you please let me know what should be the optimal value for each of the losses:
currently it is like: perceptual - 116.30898; equivariance_value - 0.28680; equivariance_jacobian - 0.64459

So after when I can start trying out the models for testing. Thank you

**Comment by AliaksandrSiarohin** [comment]
perceptual should be around 82. Rest is not that meaningfull.
