### ISSUE TITLE
VoxCeleb Dataset

### ISSUE THREAD

**Issue by Italian-PAO** [AliaksandrSiarohin/first-order-model#461]
Hi，I noticed that in your FOMM paper, the voxceleb dataset you used contains around 19000 trainning videos and 500 testing videos. But when I download this dataset following the instruction of the repo. video-preprocessing, I only get around 12000 training videos and 400 testing videos. So which size of this dataset you used in the paper? If the one with 19000 training videos, could you share a copy? And I want to use that to make a fair comparison. Thanks a lot!

**Comment by AliaksandrSiarohin** [comment]
Write me an email from your academy account.

**Comment by bajiua** [comment]
> 你好，我注意到在你的 FOMM 论文中，你使用的 voxceleb 数据集包含大约 19000 个训练视频和 500 个测试视频。但是当我按照存储库的说明下载此数据集时。视频预处理，我只得到了大约 12000 个训练视频和 400 个测试视频。那么您在论文中使用了多大的数据集？如果有19000个培训视频，你能分享一份吗？我想用它来进行公平的比较。多谢！

Hello, have you got the data set? Can you share it with me? Thank you and look forward to your reply.
