### ISSUE TITLE
save checkpoint

### ISSUE THREAD

**Issue by Fishyy599** [AliaksandrSiarohin/first-order-model#469]
Must all epoch training be completed before the checkpoints file is generated? The default epoch is 100. I still don’t see the checkpoints file after more than ten generations of training.

**Comment by AliaksandrSiarohin** [comment]
This is controlled by checkpoint_freq param, which is 50 by default. So you should see first checkpoint after 50 epochs.

**Comment by Fishyy599** [comment]
Thanks! I just read that checkpoint_freq defaults to 100. I can change the value of checkpoint_freq so that I can easily see the checkpoint.
