### ISSUE TITLE
Difference in the lengths of the driving video as well as the generated video

### ISSUE THREAD

**Issue by tushar-31093** [AliaksandrSiarohin/first-order-model#478]
Hi,
I have a driving video that is 40 seconds in duration and I would like to use this to render a motion face on an image. The rendered video is of 10 seconds duration which is a bit odd. 

Any way to fix it?

**Comment by AliaksandrSiarohin** [comment]
Set same fps for rendered video

**Comment by tushar-31093** [comment]
Isn't that already being done when you are initially extracting the fps within the variable then adding the same at the last line imageio.mimsave ?

I could be wrong here, any visual example that you could share here?

**Comment by tushar-31093** [comment]
> Set same fps for rendered video

Isn't that already being done when you are initially extracting the fps within the variable then adding the same at the last line imageio.mimsave ?

I could be wrong here, any visual example that you could share here?

**Comment by AliaksandrSiarohin** [comment]
Which demo are you using?

**Comment by tushar-31093** [comment]
> 

Sorry I didn't understand the question. There is just one demo.py file for inference right?
Also, I created my own driving video of 40 seconds / 25 FPS. And I am trying to animate my dead grandpa's face. The rendered video despite changing the FPS to either 25 or 30 still ends up being for 10 seconds duration
![e1](https://user-images.githubusercontent.com/40886260/142641615-3be71dc9-c77b-4177-91cd-4ab6021d95b1.png)
.

**Comment by tushar-31093** [comment]
> Which demo are you using?

Any idea how to go about it given setting the FPS doesn't resolve the issue? The file used is demp.py
