### ISSUE TITLE
Alpha Background

### ISSUE THREAD

**Issue by Echolink50** [AliaksandrSiarohin/first-order-model#485]
Is it possible to get the output with a transparent background? I know MP4 doesn't support alpha channel but maybe output to a png image sequence? I am sure I can use a green back ground and key it out but its seems like extra steps. Thanks everyone.

**Comment by AliaksandrSiarohin** [comment]
Alpha channel is not supported, green is the best approach I can imagine.

**Comment by Echolink50** [comment]
Thank you for the quick reply. I will close this
