### ISSUE TITLE
Trouble installing with anaconda

### ISSUE THREAD

**Issue by escuta** [AliaksandrSiarohin/first-order-model#497]
Hello, 

I have made several attempts to install first-order-model in an anaconda environment on Arch Linux. I have been able to install all the packages with python 3.7 and 3.9 but I encounter runtime problems. After attempting to upgrade various packages the process always ends with cascading dependency problems.

My last attempt to install was with:

conda create -n firstordermodel  python-dateutil==2.7.3 python==3.7
pip install -r requirements.txt 

When running: python demo.py  --config config/vox-256.yaml --driving_video ~/videos/Square.mov --source_image ~/images/face_square.png --checkpoint ~/git/first-order-model/checkpoints/vox-cpk.pth.tar --relative --adapt_scale

I get:

ImportError: Imageio Pillow requires Pillow, not PIL!

Managed to get past this only to encounter other problems.

Is there a particular version of python that should be used or are are there any updated requirements.txt files available?

Hope someone can help. Thanks.

**Comment by escuta** [comment]
Finally got it working with this procedure:

conda create -n firstordermodel anaconda=2020.02 python=3.6

edited requirements.txt to contain:

imageio==2.3.0
matplotlib==2.2.2
numpy==1.16
pandas==0.23.4
python-dateutil==2.7.3
pytz==2018.5
PyYAML==5.3
scikit-image==0.14.2
scikit-learn==0.19.2
scipy==1.1.0
torch==1.4.0
torchvision==0.5.0
tqdm==4.24.0

Then ran: pip install -r requirements.txt
Before the demo.py script would work, I needed to upgrade pillow with:
pip install --upgrade pillow

**Comment by aycaecemgul** [comment]
In python3.7 comment above did not work but i got a work around using this:

imageio==2.3.0
matplotlib==2.2.2
numpy==1.16
pandas==0.23.4
python-dateutil==2.7.3
pytz==2018.5
PyYAML==5.3
scikit-image==0.14.2
scikit-learn==0.19.2
scipy==1.1.0
torch
torchvision
tqdm==4.24.0
