### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by Tara8573** [AliaksandrSiarohin/first-order-model#498]
When running:  python demo.py --config config/vox-256.yaml --driving_video data/video/demo1.mp4 --source_image data/imgs/641.jpg --checkpoint checkpoints/vox-cpk.pth.tar --relative --adapt_scale
I got : Floating point exception

Environment:  py3.7

**Comment by waaplog** [comment]
Hello,
Did you find any solution?
Can you help me with this problem?
Best regards.

**Comment by Tara8573** [comment]
Sry, i haven't find any solution. But when i use the environment in anthor computer, this problem disappears.
