### ISSUE TITLE
bad result for a new source image?

### ISSUE THREAD

**Issue by howardgriffin** [AliaksandrSiarohin/first-order-model#5]
Dear Aliaksandr Siarohin,
When I use the checkpoint fashion.pth.tar you offerd，a test fashion video  and my own image  to run demo.py, I got the bad result. Does this indicate poor generalization performance for a new image?

**Comment by AliaksandrSiarohin** [comment]
Please post your source image and your driving video.

**Comment by howardgriffin** [comment]
> Please post your source image and your driving video.

- Source image:![3](https://user-images.githubusercontent.com/23454942/71496052-1620c400-288c-11ea-9152-3b8f67731eef.jpg)

- The driving vedio is selected from the fashion-png/test, which is named A1+O5s8cUuS.mp4 and resized to 256x256 .

- The result looks like this. As can be seen from the face and trousers，it‘s not so satisfying...
![image](https://user-images.githubusercontent.com/23454942/71496298-8b40c900-288d-11ea-957c-f3dad9ffee1e.png)

**Comment by AliaksandrSiarohin** [comment]
So in this case yes, it is a generalization problem. This fashion dataset contains only the videos of womans in dresses. So it tries to draw some sort of dreess and some long hairs.

So it need to be trained also with men videos. If you don't have men videos, you can try to create synthetic training pairs.

**Comment by howardgriffin** [comment]
> So in this case yes, it is a generalization problem. This fashion dataset contains only the videos of womans in dresses. So it tries to draw some sort of dreess and some long hairs.
> 
> So it need to be trained also with men videos. If you don't have men videos, you can try to create synthetic training pairs.

I've got it. Thank you!

**Comment by MentalGear** [comment]
Could someone elaborate on the synthetic training pairs? Did @howardgriffin  manage to get this done?
