### ISSUE TITLE
Where to find "Sup. Mat." about details of formula derivation

### ISSUE THREAD

**Issue by Zhouwangjie** [AliaksandrSiarohin/first-order-model#501]
Hi, this is really a great job! I found in the process of reading the paper that you said that there is a derivation process in _Sup. Mat._, but I couldn't find it. This might be a stupid question. Looking forward to your reply. Maybe someone could tell me. Thanks a lot in advance.

**Comment by AliaksandrSiarohin** [comment]
https://arxiv.org/pdf/2003.00196.pdf  Sec A page 12.
