### ISSUE TITLE
Unable to get crop-video.py to work in collab

### ISSUE THREAD

**Issue by devonluongo** [AliaksandrSiarohin/first-order-model#502]
When I run:

`!python first-order-model/crop-video.py --inp 'gdrive/MyDrive/Colab Notebooks/Deep Fakes/videos/barack_obama_short.mp4'`

it outputs:

250it [00:37,  6.75it/s] 

exits successfully, but doesn't modify the source video. I can see from the source code that it's supposed to output commands. What are these commands and how to I interact with them to modify the source image?

**Comment by AliaksandrSiarohin** [comment]
It creates new video crop.mp4.

**Comment by zhaochunhui-0723** [comment]
crop.mp4 which directory is this video in
