### ISSUE TITLE
Is there any way to fake add or mechanical voice along with video!!

### ISSUE THREAD

**Issue by snehitvaddi** [AliaksandrSiarohin/first-order-model#51]
I tried it, and it looks super dope. If there is an option to mimic voice to a specified voice it could be the best. I tried some sources like Lyrebird which is not working as they specified. Are there any other ways to create a fake voice??

**Comment by AliaksandrSiarohin** [comment]
Don't really get what you mean, probably see related issue #47

**Comment by snehitvaddi** [comment]
I mean, since in this repo we can only create a fake video but no audio right!!
I am asking how to add a fake voice to the deep fake video.

Example: Assume we giving an input image of 'Jack' and a  video of 'Trump' and We get an output as Jack acting like Trump. I am asking can we also fake voice like replacing the voice of 'Trump' with voice of 'Jack'..??
Hope you can understand now.

**Comment by AliaksandrSiarohin** [comment]
I belive there are deep learning methods that can do this type of manipulations but, I'm not familiar with them. Sorry.
