### ISSUE TITLE
About paper & code question

### ISSUE THREAD

**Issue by samsara-ku** [AliaksandrSiarohin/first-order-model#513]
Hello, first i'm appreciate your great work in this field.

I've a question about code and paper.

In your paper, I understand $T_{S<-D}$ is called _**sparse motion field**_ and that is a first-step of your motion transfer work.

Then, in this situation:

1. Does sparse motion field $T_{S<-D}$ give a optical flow from _driving video_ **D** to _source image_ **S**?
2. If above question is right, why you write some codes in this way?

In modules/dense_motion.py,
```
sparse_motion = self.create_sparse_motions(source_image, kp_driving, kp_source)
```

I couldn't understand why we **_backward warping flow_**,  which moves pixel of driving video **D** to source image **S**, apply that backward flow into source image.

CMIIW, I think the right way is warping the source image using **_inverse of backward warping flow_**.

Thank you.

**Comment by AliaksandrSiarohin** [comment]
1.Right. 
2. Applying forward optical flow is more complicated since you will have multiple values that lend to same cell plus a lot of holes. Thus pytorch only support applying backward optical flow.

**Comment by samsara-ku** [comment]
Thanks for your answers, @AliaksandrSiarohin .

I understand what you talk about it: The optical flow argument of `F.grid_sample(img, optical_flow)` should be **_backward optical flow_**.

Then, I need one more thing to sure about it: 

In your paper, because there are misalignment between source and driving image.

Then it is okay to understand like this?:

**_"Applying optical flow to source image is up for aligning source image to driving image."_**

**Comment by AliaksandrSiarohin** [comment]
Yes.

**Comment by samsara-ku** [comment]
Thanks a million :)
