### ISSUE TITLE
ffmpeg error in Googlecolab 

### ISSUE THREAD

**Issue by bretasvj** [AliaksandrSiarohin/first-order-model#516]
#For the last couple of months I've been trying to using FOMM for portrait animation with no success
#Always the same error. Can someone help me ?

ModuleNotFoundError                       Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/imageio/plugins/ffmpeg.py](https://localhost:8080/#) in _get_ffmpeg_api()
     58         try:
---> 59             import imageio_ffmpeg
     60         except ImportError:

ModuleNotFoundError: No module named 'imageio_ffmpeg'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
8 frames
[/usr/local/lib/python3.7/dist-packages/imageio/plugins/ffmpeg.py](https://localhost:8080/#) in _get_ffmpeg_api()
     60         except ImportError:
     61             raise ImportError(
---> 62                 "To use the imageio ffmpeg plugin you need to "
     63                 "'pip install imageio-ffmpeg'"
     64             )

ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by AliaksandrSiarohin** [comment]
Add cell:
!pip install imageio-ffmpeg

**Comment by bretasvj** [comment]
can you tell where should i add it ?
really a beguinner here :) open for any tips 

thanks for the help!

**Comment by AliaksandrSiarohin** [comment]
Before everything.

**Comment by bretasvj** [comment]
now i was hable to generate the menu 
but got stopped by this new error 

TypeError                                 Traceback (most recent call last)
[<ipython-input-2-bc82fa75d0a0>](https://localhost:8080/#) in generate(button)
    418         for frame in reader:
    419                 driving_video.append(frame)
--> 420         generator, kp_detector = load_checkpoints(config_path='config/%s-256.yaml' % model.value, checkpoint_path=filename)
    421 	predictions = make_animation(
    422                 skimage.transform.resize(numpy.asarray(selected_image), (256, 256)),

[/content/demo.py](https://localhost:8080/#) in load_checkpoints(config_path, checkpoint_path, cpu)
     25 
     26     with open(config_path) as f:
---> 27         config = yaml.load(f)
     28 
     29     generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],

TypeError: load() missing 1 required positional argument: 'Loader'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-bc82fa75d0a0>](https://localhost:8080/#) in generate(button)
    418         for frame in reader:
    419                 driving_video.append(frame)
--> 420         generator, kp_detector = load_checkpoints(config_path='config/%s-256.yaml' % model.value, checkpoint_path=filename)
    421 	predictions = make_animation(
    422                 skimage.transform.resize(numpy.asarray(selected_image), (256, 256)),

[/content/demo.py](https://localhost:8080/#) in load_checkpoints(config_path, checkpoint_path, cpu)
     25 
     26     with open(config_path) as f:
---> 27         config = yaml.load(f)
     28 
     29     generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],

TypeError: load() missing 1 required positional argument: 'Loader'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-bc82fa75d0a0>](https://localhost:8080/#) in generate(button)
    418         for frame in reader:
    419                 driving_video.append(frame)
--> 420         generator, kp_detector = load_checkpoints(config_path='config/%s-256.yaml' % model.value, checkpoint_path=filename)
    421 	predictions = make_animation(
    422                 skimage.transform.resize(numpy.asarray(selected_image), (256, 256)),

[/content/demo.py](https://localhost:8080/#) in load_checkpoints(config_path, checkpoint_path, cpu)
     25 
     26     with open(config_path) as f:
---> 27         config = yaml.load(f)
     28 
     29     generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],

TypeError: load() missing 1 required positional argument: 'Loader'
