### ISSUE TITLE
keypoints padding

### ISSUE THREAD

**Issue by mhubii** [AliaksandrSiarohin/first-order-model#52]
isnt it a problem that you set the padding for the keypoints to 0 [here](https://github.com/AliaksandrSiarohin/first-order-model/blob/bb738aa0a900a8c4e7d9deb105d27e6f7ea18ef7/modules/keypoint_detector.py#L20)? This alters the shape of the output, and therefore the position of the keypoints by 1/100 or so, which shouldnt effect the results, but I was wondering

**Comment by AliaksandrSiarohin** [comment]
Yes. This is a problem, but it does not affect results that much. Because I found this problem after I trained all the models, I decide not to retrain and just add additional parameter pad. So if you training from scratch you should use pad=3.
