### ISSUE TITLE
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

### ISSUE THREAD

**Issue by AbdullahRamadan07** [AliaksandrSiarohin/first-order-model#520]
I have a problem after i run the code and upload the image and the video there was an error and it was "MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://none/?"
what should I do?

**Comment by convurt** [comment]
Same error here
[/usr/local/lib/python3.7/dist-packages/requests/models.py](https://localhost:8080/#) in prepare_url(self, url, params)
    386             error = error.format(to_native_string(url, 'utf8'))
    387 
--> 388             raise MissingSchema(error)
    389 
    390         if not host:

MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://none/?

**Comment by YichenViolet** [comment]
我发现了原因是"https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=https://yadi.sk/d/lEw8uRm140L_eQ&path=/"这个网站链接失效了，无法下载schema，导致MissingSchema

**Comment by SaraConcasUnica** [comment]
I have the same problem

**Comment by hannibalbarx** [comment]
same error in colab. same code was working before. i guess the model file moved?

MissingSchema                             Traceback (most recent call last)

[<ipython-input-2-c6ecbcc6e5a1>](https://localhost:8080/#) in generate(button)
    410         filename = model.value + ('' if model.value == 'fashion' else '-cpk') + '.pth.tar'
    411         if not os.path.isfile(filename):
--> 412                 download = requests.get(requests.get('https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=https://yadi.sk/d/lEw8uRm140L_eQ&path=/' + filename).json().get('href'))
    413                 with open(filename, 'wb') as checkpoint:
    414                         checkpoint.write(download.content)

5 frames

[/usr/local/lib/python3.7/dist-packages/requests/models.py](https://localhost:8080/#) in prepare_url(self, url, params)
    386             error = error.format(to_native_string(url, 'utf8'))
    387 
--> 388             raise MissingSchema(error)
    389 
    390         if not host:

MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://none/?`

**Comment by hannibalbarx** [comment]
looks like too many downloads of the model so yandex has blocked further downloads.

**Comment by nonlin** [comment]
can anyone create a new upload with download link for us to use? I just hopped into this and can't get the model to use this.

**Comment by hannibalbarx** [comment]
> can anyone create a new upload with download link for us to use? I just hopped into this and can't get the model to use this.

the model is already available on google drive

https://drive.google.com/drive/folders/1PyQJmkdCsAkOYwUyaj_l-l0as-iLDgeH

**Comment by graphemecluster** [comment]
The issue has now been fixed.
