### ISSUE TITLE
[BUG] Resource not found in yandex,  Model file is lost!

### ISSUE THREAD

**Issue by mininxd** [AliaksandrSiarohin/first-order-model#521]
https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=https://yadi.sk/d/lEw8uRm140L_eQ&path=/

{"message":"Не удалось найти запрошенный ресурс.","description":"Resource not found.","error":"DiskNotFoundError"}

**Comment by h3d-longnsp** [comment]
- https://disk.yandex.ru/d/lEw8uRm140L_eQ Here is the original models link. It isn't lost, it's just exceeded download limit. You can save the folder to Yandex.Disk and download it from there. Make sure your folder is public and copy the url after `disk.yandex.ru/d/` and replace it in that line of code (between `disk.yandex.ru/d/` and `&path`)

**Comment by h3d-longnsp** [comment]
- Model files are still there, the link just exceeded download limit. To fix that you can go to the link in `public_key`: https://disk.yandex.ru/d/lEw8uRm140L_eQ , click `Save to Yandex.disk to download`. After that, access your yandex disk and make sure the downloaded folder is shared (it located at `/Download/first-order-model`). Then, right click the folder, choose `Share` then `Copy link` 
![image](https://user-images.githubusercontent.com/99666567/196719854-d4761b51-df95-4e77-84e6-2794c0cc4086.png)
- Finally, replace the link in that line of code with yours (between `public_key=` and `&path=`). The colab should run correctly this time.
![image](https://user-images.githubusercontent.com/99666567/196720264-46b28d64-03f9-41d9-a2c6-2884bbc574de.png)

**Comment by longnsp** [comment]
> https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=https://yadi.sk/d/lEw8uRm140L_eQ&path=/
> 
> {"message":"Не удалось найти запрошенный ресурс.","description":"Resource not found.","error":"DiskNotFoundError"}

- Model files are still there, the link just exceeded download limit. To fix that you can go to the link in `public_key`: https://disk.yandex.ru/d/lEw8uRm140L_eQ , click `Save to Yandex.disk to download`. After that, access your yandex disk and make sure the downloaded folder is shared (it located at `/Download/first-order-model`). Then, right click the folder, choose `Share` then `Copy link` 
![image](https://user-images.githubusercontent.com/99666567/196719854-d4761b51-df95-4e77-84e6-2794c0cc4086.png)
- Finally, replace the link in that line of code with yours (between `public_key=` and `&path=`). The colab should run correctly this time.
![image](https://user-images.githubusercontent.com/99666567/196720264-46b28d64-03f9-41d9-a2c6-2884bbc574de.png)

**Comment by exebook** [comment]
Can someone please make this model available somewhere else? I cannot login to Yandex, they require a phone number.

**Comment by longnsp** [comment]
> Can someone please make this model available somewhere else? I cannot login to Yandex, they require a phone number.

- You can download the models you need and upload to google drive then use drive api. Please read their documents [here](https://developers.google.com/drive/api/v3/reference) as I already made it work using yandex

**Comment by mininxd** [comment]
thanks y'all
