### ISSUE TITLE
Syntax error running demo.py

### ISSUE THREAD

**Issue by AmarBouali** [AliaksandrSiarohin/first-order-model#53]
Hello !

Running the command

python demo.py  --config config/fashion-256.yaml --driving_video .//Skills-1.mp4 --source_image ./single.jpeg --checkpoint ./checkpoints --relative --adapt_scale

I got the following error

File "demo.py", line 27
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                                                                    ^
SyntaxError: invalid syntax
Any hint ? Thanks !

**Comment by AliaksandrSiarohin** [comment]
You should use python3

**Comment by AmarBouali** [comment]
> You should use python3

Oops. Indeed. It works now.
Thanks !
