### ISSUE TITLE
is it possible denormalizing the normalized keypoints ?

### ISSUE THREAD

**Issue by m-pektas** [AliaksandrSiarohin/first-order-model#540]
I need to denormalize the normalized keypoints for my work. There is relativity in the normalizing process. is denormalizing possible?

**Comment by AliaksandrSiarohin** [comment]
Depends on what you know, if it is only normalized keypoints then no.

**Comment by m-pektas** [comment]
Yes,  I asked that can I denormalize it when I know just normalized keypoints? Thanks for your reply @AliaksandrSiarohin .
