### ISSUE TITLE
Any information regarding which Python version was used in this repo?

### ISSUE THREAD

**Issue by qaixerabbas** [AliaksandrSiarohin/first-order-model#542]
I am trying to run this code locally on my Windows Machine. Following libraries specific versions are not available while using Python 3.9.

```
pandas==0.23.4
scikit-image==0.14.2
scikit-learn==0.19.2
scipy==1.1.0
torch==1.0.0
matplotlib==2.2.2
```

I have installed other requirements successfully. As per my intuition if we know which version of Python was used in this repo then we can install the above libraries using that specific Python version. Any information/knowledge in this regard is highly appreciated.

**Comment by arkilis** [comment]
Since it is an old repo, suggest you have a try with python3.8

**Comment by 542154968** [comment]
python version 3.7.2

requirements.txt  ->  numpy==1.15.0

**Comment by qaixerabbas** [comment]
@arkilis and @542154968  thank you for your help. I was able to run the code without specifying the libraries version. This may help others in future while trying to run the code.
