### ISSUE TITLE
Import "demo" could not be resolved

### ISSUE THREAD

**Issue by paulreichling** [AliaksandrSiarohin/first-order-model#543]
Trying to run the collab demo and I get this. I already saw https://github.com/AliaksandrSiarohin/first-order-model/issues/528 and this did not fix my issue. Any help would be appreciated 

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-5-dbd18151b569>](https://localhost:8080/#) in <module>
----> 1 from demo import load_checkpoints
      2 generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
      3                             checkpoint_path='/content/gdrive/My Drive/first-order-motion-model/vox-cpk.pth.tar')

[/content/first-order-model/demo.py](https://localhost:8080/#) in <module>
     15 from animate import normalize_kp
     16 
---> 17 import ffmpeg
     18 from os.path import splitext
     19 from shutil import copyfileobj

ModuleNotFoundError: No module named 'ffmpeg'

**Comment by graphemecluster** [comment]
The old demo is no longer maintained. Please use the new demo.

---

If you insist on using it, please run `%pip install ffmpeg-python imageio-ffmpeg`.

**Comment by paulreichling** [comment]
Thank you for the help!

**Comment by paburo-san666** [comment]
> The old demo is no longer maintained. Please use the new demo.
> 
> If you insist on using it, please run `%pip install ffmpeg-python imageio-ffmpeg`.

what is the new demo?!!!!!!!!!!!!!!!!!!!!!!!

**Comment by graphemecluster** [comment]
@paburo-san666 [demo.ipynb](https://github.com/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb) is the new demo, and [old_demo.ipynb](https://github.com/AliaksandrSiarohin/first-order-model/blob/master/old_demo.ipynb) is the old demo.
