### ISSUE TITLE
error

### ISSUE THREAD

**Issue by smrtknow** [AliaksandrSiarohin/first-order-model#559]
something with this line
`from demo import load_checkpoints, make_animation  # type: ignore (local file)`
![image](https://user-images.githubusercontent.com/130289340/230771093-5779c9bc-fde6-4564-807b-4fe7ff6e07f8.png)

the error done is

> ImportError                               Traceback (most recent call last)
> [<ipython-input-6-d58cce7e7ff1>](https://localhost:8080/#) in <cell line: 14>()
>      12 import warnings
>      13 from base64 import b64encode
> ---> 14 from demo import load_checkpoints, make_animation  # type: ignore (local file)
>      15 from google.colab import files, output
>      16 from IPython.display import HTML, Javascript
> 
> 3 frames
> [/content/augmentation.py](https://localhost:8080/#) in <module>
>      10 
>      11 from skimage.transform import resize, rotate
> ---> 12 from skimage.util import pad
>      13 import torchvision
>      14 
> 
> ImportError: cannot import name 'pad' from 'skimage.util' (/usr/local/lib/python3.9/dist-packages/skimage/util/__init__.py)
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.
> ---------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/130289340/230771129-b2630140-48dd-4791-866e-647df812a4c4.png)

**Comment by paburo-san666** [comment]
did you fix it?

**Comment by ilovedogs1235** [comment]
this is not fucking helpful
