### ISSUE TITLE
Can't use an own video for colab demo

### ISSUE THREAD

**Issue by paburo-san666** [AliaksandrSiarohin/first-order-model#566]
I have been getting a lot of issues with colab demo since a while. I tried all of the solution that are around  (#545 #564 #565). The demo works without any problem until I use an own video. This appears:

![2023-05-04 (7)](https://user-images.githubusercontent.com/102203446/236247516-45c47db8-11c3-4d5a-9df8-0492a831a7b6.png)

There is something I can do?

**Comment by ignat-admin** [comment]
https://github.com/imageio/imageio/issues/968 
if you solve all the problems in the code, send it to me, I couldn't fix all the mistakes

**Comment by ignat-admin** [comment]
i was able to fix the program but you need to restart the runtime before running the code
https://colab.research.google.com/drive/1NLql5hmZo1N1qugyDtuGw9RjTNfC19MW

**Comment by ignat-admin** [comment]
first run the code, restart the runtime, reload the page, restart the runtime and it should work

**Comment by prismaticcabyss** [comment]
![image](https://github.com/AliaksandrSiarohin/first-order-model/assets/133512467/2a272a3d-18d7-4805-9c3e-ca91ef4a7801)
I used the updated program which fixed the issue above, but I've been getting this error instead

**Comment by paburo-san666** [comment]
> i was able to fix the program but you need to restart the runtime before running the code https://colab.research.google.com/drive/1NLql5hmZo1N1qugyDtuGw9RjTNfC19MW

there is any kind to contact with you directly? I'm seriously struggling with running your fix

**Comment by paburo-san666** [comment]
@AliaksandrSiarohin merged one of the pull request but still passing over my issue :/
