### ISSUE TITLE
The model of fashion.pth.tar can not down,because it is error.

### ISSUE THREAD

**Issue by cheersgocheersgo** [AliaksandrSiarohin/first-order-model#579]
The model of fashion.pth.tar can not down,because it is error.
It shows that:
(fashion.pth.tar: The format of this archive is unknown or the data has been corrupted)
Which one can help me down the model.
  Thanks very much.

**Comment by AliaksandrSiarohin** [comment]
It is not a tar. Use as it as checkpoint. Sorry for confusion.
