### ISSUE TITLE
How to make the image have the same pose as the first driving frame?

### ISSUE THREAD

**Issue by molo32** [AliaksandrSiarohin/first-order-model#59]
the "source image"
at the beginning it has a pose or angle that is not the same as my video driving.
therefore the "source image" has another angle throughout the video, I want
 "source image" has the same angle as the driving head.

for example if "driving" is facing the camera "source image" should be facing the camera

there is way to force this without looking for a "source image" with the same angle of the head of the first frame of driving

**Comment by AliaksandrSiarohin** [comment]
See #54
