### ISSUE TITLE
The KeypointDetector checkpoint does not support 64*64 input

### ISSUE THREAD

**Issue by YsummerQ** [AliaksandrSiarohin/first-order-model#598]
In FOMM paper, it says "In order to reduce memory and computational requirements of our model, the keypoint detector and dense motion predictor both work on resolution of 64 × 64 "
But when I tried to use the KeypointDetector in pre-trained checkpoint, I got an error when I entered a 64 × 64 frame, saying that I had downsampled too many times.
It seems that the paper is talking about training KeypointDetector using 64 × 64 frames, however, the pre-trained KeypointDetector is training on 256 × 256 frames

**Comment by AliaksandrSiarohin** [comment]
Hi,
The Keypoint detector has 4x downsampling as an initial layer inside the module. So you should provide 256 inputs to it.
Regards, AS
