### ISSUE TITLE
fashion checkpoint Error on demo.py on colab

### ISSUE THREAD

**Issue by nikky4D** [AliaksandrSiarohin/first-order-model#6]
i installed in google colab using typical, with torch version 1.0.0
`!git clone `https://github.com/AliaksandrSiarohin/first-order-model.git`
`cd first-order-model/`
`!pip install -r requirements.txt`

I download the fashion.pth.tar checkpoint, and put it in a folder called first-order-model/checkpoints/fashion.pth.tar

I then put the source image and driving videos in folder data. 

When I run the demo: 
`!python demo.py  --config config/fashion-256.yaml --driving_video data/vid.mp4 --source_image data/img3.jpg --checkpoint checkpoints/fashion.pth.tar --relative --adapt_scale
`
I get the following errors:

> /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> WARNING:root:Warning: the frame size for reading (352, 640) is different from the source frame size (640, 352).
> WARNING:root:Warning: the frame size for reading (352, 640) is different from the source frame size (640, 352).
> /usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
>   warn("The default mode, 'constant', will be changed to 'reflect' in "
> /usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
>   warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
> Traceback (most recent call last):
>   File "demo.py", line 92, in <module>
>     generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint)
>   File "demo.py", line 35, in load_checkpoints
>     checkpoint = torch.load(checkpoint_path)
>   File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 367, in load
>     return _load(f, map_location, pickle_module)
>   File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 545, in _load
>     deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
> RuntimeError: unexpected EOF, expected 480726 more bytes. The file might be corrupted.
> terminate called after throwing an instance of 'c10::Error'
>   what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:341, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:341)
> frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fe861d96fe1 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
> frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fe861d96dfa in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
> frame #2: THStorage_free + 0xca (0x7fe862a0caea in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
> frame #3: <unknown function> + 0x4b6317 (0x7fe89c26a317 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
> frame #4: python3() [0x54f6e6]
> frame #5: python3() [0x5734e0]
> frame #6: python3() [0x4b1a28]
> frame #7: python3() [0x589078]
> frame #8: python3() [0x5ade68]
> frame #9: python3() [0x5ade7e]
> frame #10: python3() [0x5ade7e]
> frame #11: python3() [0x5ade7e]
> frame #12: python3() [0x56be56]
> <omitting python frames>
> frame #18: __libc_start_main + 0xe7 (0x7fe8bd840b97 in /lib/x86_64-linux-gnu/libc.so.6)

The error seems to be occuring at torch.load(). Since, If I only run 
`    checkpoint = torch.load('checkpoints/fashion.pth.tar')
`
Then, the error appears:

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-31-8e4c83aa2aae> in <module>()
> ----> 1 checkpoint = torch.load('checkpoints/fashion.pth.tar')
> 
> 1 frames
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in _load(f, map_location, pickle_module)
>     543     for key in deserialized_storage_keys:
>     544         assert key in deserialized_objects
> --> 545         deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
>     546         offset = None
>     547 
> 
> RuntimeError: unexpected EOF, expected 480726 more bytes. The file might be corrupted.

The issue appear to be with fashion.pth.tar file. Using taichi-adv-cpk.pth.tar does not produce the error.

**Comment by AliaksandrSiarohin** [comment]
What is the size of the checkpoint (in megabytes)? Have you tried to redownload and reupload to colab?

**Comment by nikky4D** [comment]
Thanks. It was an error on the colab upload. It worked with a reupload to colab. Also, for best results, what would you recommend for input video and the input image in terms of image size and background?

**Comment by AliaksandrSiarohin** [comment]
Ideally the videos (images) should be similar to the the train distribution. In case of fashion these are images of woman in dresses on a white background. Similar to one presented in the main page of the repository.

**Comment by nikky4D** [comment]
Thanks for the information and great work. Especially in the ease of use compared to other works.
