### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by lookbothways** [AliaksandrSiarohin/first-order-model#61]
Recent commit causes error here.

```from demo import load_checkpoints
generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
                            checkpoint_path='/content/gdrive/My Drive/first-order-motion-model/vox-cpk.pth.tar')

----------------------------------------------------

AttributeError                            Traceback (most recent call last)
<ipython-input-6-dbd18151b569> in <module>()
      1 from demo import load_checkpoints
      2 generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
----> 3                             checkpoint_path='/content/gdrive/My Drive/first-order-motion-model/vox-cpk.pth.tar')

/content/first-order-model/demo.py in load_checkpoints(config_path, checkpoint_path)
     24 
     25     with open(config_path) as f:
---> 26         config = yaml.load(f, Loader=yaml.FullLoader)
     27 
     28     generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],

AttributeError: module 'yaml' has no attribute 'FullLoader```

**Comment by ZeroCool940711** [comment]
@lookbothways after searching a bit I found out its probably because the version of PyYAML you have installed is probably older than version 5.1 which doesnt have the FullLoader class, I found it on [this stackoverflow post](https://stackoverflow.com/a/55553392) , if you want to solve it upgrade PyYAML to the latest version with `pip install -U PyYAML`, here is the comment in case you dont want to go to that link.

```
The `FullLoader` class is only available in PyYAML 5.1 and later. Version 5.1 was [released on March 13, 2019](https://pyyaml.org/wiki/PyYAML#history) and has probably not filtered down to many distributions yet.

You can check the version of PyYAML by inspecting `yaml.__version__`:

    Python 2.7.15 (default, Oct 15 2018, 15:24:06) 
    [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import yaml
    >>> yaml.__version__
    '3.13'

If you are managing packages with `pip`, you can upgrade to the current release by running:

    pip install -U PyYAML
```

**Comment by ZeroCool940711** [comment]
@lookbothways this should have been fixed right now by PR #1 which AliaksandrSiarohin just merged. Can you try to see if this is fixed for you and if it is can you close this issue?

**Comment by tomreznikov** [comment]
Hey, I tried this now - Still not fixed from my end

**Comment by ZeroCool940711** [comment]
@tomreznikov make sure you're using PyYAML 5.1 or higher, check my first comment on how to do it. If it is still not working and you have PyYAML 5.1 then I will see whats happening but it should work if you have PyYAML 5.1, I do have PyYAML 5.1.1 and it works for me.

**Comment by tomreznikov** [comment]
Hey, I have PyYAML 5.3.1  and still not working

**Comment by ZeroCool940711** [comment]
I don't understand why it doesn't work , I installed PyYAML 5.3.1 and it still works perfectly, I was getting another error that will be fixed by PR #63 but it does work for me .-.

**Comment by tomreznikov** [comment]
Any chance it's because I'm working from Colab Notebook?

**Comment by ZeroCool940711** [comment]
mmm, could be, im running it on my own computer so, not sure if it works on colab or not, have to test it but im not a big fan of colab so someone else could be better for that.

**Comment by DEEPFAKEFAKER** [comment]
I'm having the same problem, anyway to revert that so Colab Notebook still works?

**Comment by ZeroCool940711** [comment]
Ok, this is weird, I tried the `demo.ipynb` on Colab and it works okay for me, at least the one from here on the repository, not sure if you guys have a modified version or an older version but the latest one works for me .-.

**Comment by DEEPFAKEFAKER** [comment]
I don't know what am I doing wrong then, just used the file here in the repository, factory reset the runtime and it's still giving me that error.

**Comment by AliaksandrSiarohin** [comment]
Same happens for me, my colab yaml is 3.13. It is possible to install yaml in colab, but I guess it will be easier if it works straight away. So this warning is probably not a big deal.

**Comment by Usmaniatech** [comment]
`pip install PyYAML==5.3.1`
If using google collab
`!pip install PyYAML==5.3.1`

Probably after running this, it'll require you to restart the runtime, better to run the file from the top again. And if it gives the error for 

> No module named demo
Write
`import demo`
@lookbothways
