### ISSUE TITLE
Is there a way for the source video be a webcam?

### ISSUE THREAD

**Issue by Tomas1337** [AliaksandrSiarohin/first-order-model#68]
And have the output be real time as well?

**Comment by Jefersonwulf** [comment]
Currently there is no way to do this, but I believe that most likely someone will take this code and develop it to use it in a service like this in real time

**Comment by Tomas1337** [comment]
Let me be the one!
I shall try my best as a noob

**Comment by Jefersonwulf** [comment]
Well, more noob than me you are not ... I still haven't learned how to train my own models

**Comment by Lolologist** [comment]
I love this idea! Will keep my ears open to hear something of this sort.

**Comment by AliaksandrSiarohin** [comment]
I guess you can refer to this repository https://github.com/alievk/avatarify
