### ISSUE TITLE
Cropping produces no output on some videos

### ISSUE THREAD

**Issue by Simon-R-IT** [AliaksandrSiarohin/first-order-model#69]
Hi,

I might be doing this wrong. I'm asking the program to crop a 5 seconds video I recorded on a phone.
python crop-video.py --inp sup-mat\IMG_1130.mp4

I have a batch of videos of me talking in froont of the camera (short 5-10 seconds videos, 1920x1080). But some of those just don't produce anything when i try to crop them. No error message, no ffmpeg command. The script just stops.

it keeps happening to hose failed videos no matter how many times I try

**Comment by AliaksandrSiarohin** [comment]
It is hard to say without a videos. Crop-video.py is only give a suggestion, so there are a lot of heuristics there. The face should stay pretty close to the initial frame for 150 frames, closeness is measured using iou between initial face bbox and cureent face bbox. So you could either decrease min_frames or decrease iou_with_initial or record videos where head moves near initial position.
