### ISSUE TITLE
Erro when try to run

### ISSUE THREAD

**Issue by Jefersonwulf** [AliaksandrSiarohin/first-order-model#70]
When I tried to run run.py it gave the following error

```
(base) PS C:\Users\jefer\Desktop\first-order-model-master> python run.py --config config/vox-adv-256_clone.yaml --device_ids 0
Use predefined train-test split.
Training...
  0%|                                                                                                                                                                       | 0/150 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 77, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "C:\Users\jefer\Desktop\first-order-model-master\train.py", line 50, in train
    for x in dataloader:
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jefer\Desktop\first-order-model-master\frames_dataset.py", line 154, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "C:\Users\jefer\Desktop\first-order-model-master\frames_dataset.py", line 103, in __getitem__
    path = np.random.choice(glob.glob(os.path.join(self.root_dir, name + '*.mp4')))
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

**Comment by AliaksandrSiarohin** [comment]
Your filenames is not correct. Either not use id_sampling or rename your files as explained here https://github.com/AliaksandrSiarohin/first-order-model/blob/83d8d7be6a24bba8cf985d126c1eabab906d85bf/config/taichi-256.yaml#L7

**Comment by Jefersonwulf** [comment]
> Your filenames is not correct. Either not use id_sampling or rename your files as explained here
> 
> https://github.com/AliaksandrSiarohin/first-order-model/blob/83d8d7be6a24bba8cf985d126c1eabab906d85bf/config/taichi-256.yaml#L7

How much VRAM does my video card need?
RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 8.00 GiB total capacity; 5.28 GiB already allocated; 973.55 MiB free; 5.34 GiB reserved in total by PyTorch)

**Comment by AliaksandrSiarohin** [comment]
You should adjust the batch size to fit in the memory.

**Comment by Jessicall** [comment]
@AliaksandrSiarohin Hello,could you give me a favor,please?
What should i do?

Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/remote-home/my/pycharmprojects/first-order-model/train.py", line 50, in train
    for x in dataloader:
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
imageio.core.format.CannotReadFrameError: Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/imageio/plugins/ffmpeg.py", line 565, in _read_frame_data
    (len(s), framesize))
RuntimeError: Frame is 0 bytes, but expected 2030400.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/remote-home/my/pycharmprojects/first-order-model/frames_dataset.py", line 154, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "/remote-home/my/pycharmprojects/first-order-model/frames_dataset.py", line 116, in __getitem__
    video_array = read_video(path, frame_shape=self.frame_shape)
  File "/remote-home/my/pycharmprojects/first-order-model/frames_dataset.py", line 43, in read_video
    video = np.array(mimread(name))
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/imageio/core/functions.py", line 286, in mimread
    for im in reader:
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/imageio/core/format.py", line 397, in iter_data
    im, meta = self._get_data(i)
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/imageio/plugins/ffmpeg.py", line 396, in _get_data
    result, is_new = self._read_frame()
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/imageio/plugins/ffmpeg.py", line 585, in _read_frame
    s, is_new = self._read_frame_data()
  File "/usr/local/miniconda3/envs/animation1/lib/python3.5/site-packages/imageio/plugins/ffmpeg.py", line 571, in _read_frame_data
    raise CannotReadFrameError(fmt % (self._pos, err1, err2))
imageio.core.format.CannotReadFrameError: Could not read frame 446:
Frame is 0 bytes, but expected 2030400.
=== stderr ===
ffmpeg version N-86111-ga441aa90e8-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-8) 20170304
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 63.100 / 55. 63.100
  libavcodec     57. 96.101 / 57. 96.101
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 89.101 /  6. 89.101
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/remote-home/my/pycharmprojects/first-order-model/data/fashion-dataset/train/91w4r-YTBlS.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1mp42
    creation_time   : 2016-03-26T05:08:17.000000Z
  Duration: 00:00:14.98, start: 0.000000, bitrate: 444 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 720x940 [SAR 1:1 DAR 36:47], 439 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2016-03-26T05:08:15.000000Z
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 3 kb/s (default)
    Metadata:
      creation_time   : 2016-03-26T05:08:13.000000Z
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1mp42
    encoder         : Lavf57.72.101
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 720x940 [SAR 1:1 DAR 36:47], q=2-31, 487296 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
ffmpeg version N-86111-ga441aa90e8-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-8) 20170304
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 63.100 / 55. 63.100
  libavcodec     57. 96.101 / 57. 96.101
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 89.101 /  6. 89.101
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/remote-home/my/pycharmprojects/first-order-model/data/fashion-dataset/train/91w4r-YTBlS.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1mp42
    creation_time   : 2016-03-26T05:08:17.000000Z
  Duration: 00:00:14.98, start: 0.000000, bitrate: 444 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 720x940 [SAR 1:1 DAR 36:47], 439 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2016-03-26T05:08:15.000000Z
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 3 kb/s (default)
    Metadata:
      creation_time   : 2016-03-26T05:08:13.000000Z
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1mp42
    encoder         : Lavf57.72.101
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 720x940 [SAR 1:1 DAR 36:47], q=2-31, 487296 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2016-03-26T05:08:15.000000Z
      encoder         : Lavc57.96.101 rawvideo
frame=  135 fps=0.0 q=-0.0 size=  267680kB time=00:00:04.50 bitrate=487296.0kbits/s speed=8.96x    
frame=  331 fps=330 q=-0.0 size=  656311kB time=00:00:11.03 bitrate=487296.0kbits/s speed=  11x    
frame=  447 fps=326 q=-0.0 Lsize=  886317kB time=00:00:14.90 bitrate=487296.0kbits/s speed=10.9x    
video:886317kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by AliaksandrSiarohin** [comment]
@Jessicall no idea what you are doing.

**Comment by Jefersonwulf** [comment]
> > Your filenames is not correct. Either not use id_sampling or rename your files as explained here
> > https://github.com/AliaksandrSiarohin/first-order-model/blob/83d8d7be6a24bba8cf985d126c1eabab906d85bf/config/taichi-256.yaml#L7
> 
> How much VRAM does my video card need?
> RuntimeError: CUDA out of memory. Tried to allocate 1.13 GiB (GPU 0; 8.00 GiB total capacity; 5.28 GiB already allocated; 973.55 MiB free; 5.34 GiB reserved in total by PyTorch)

**Comment by Jefersonwulf** [comment]
> Your filenames is not correct. Either not use id_sampling or rename your files as explained here
> 
> https://github.com/AliaksandrSiarohin/first-order-model/blob/83d8d7be6a24bba8cf985d126c1eabab906d85bf/config/taichi-256.yaml#L7

Sorry but I didn't really understand how to rename my files, for example

I created a folder with a name that I want for the new checkpoint with the name "training" in the root

![image](https://user-images.githubusercontent.com/62947736/78460981-f0ca0000-769b-11ea-8437-a64841f4eb56.png)

Inside them I created the two folders as described there

![image](https://user-images.githubusercontent.com/62947736/78461023-47cfd500-769c-11ea-9b42-a6d9e90dbe44.png)

And inside the training folder, the video file that I'm going to use, in this case I'm using one of the ones you previously provided

![image](https://user-images.githubusercontent.com/62947736/78461060-82d20880-769c-11ea-90d1-967fa43d5620.png)

In the .YAML settings I left it with the path to the "training" folder

![image](https://user-images.githubusercontent.com/62947736/78461129-d93f4700-769c-11ea-8008-ef03a769a604.png)

So when I run the code it gives the same error ...

```
(base) PS C:\Users\jefer\Desktop\first-order-model-master> python run.py --config config/vox-adv-256_clone.yaml --device_ids 0                                                                                                                  Use predefined train-test split.
Training...
  0%|                                                                                          | 0/150 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 77, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "C:\Users\jefer\Desktop\first-order-model-master\train.py", line 50, in train
    for x in dataloader:
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jefer\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jefer\Desktop\first-order-model-master\frames_dataset.py", line 154, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "C:\Users\jefer\Desktop\first-order-model-master\frames_dataset.py", line 103, in __getitem__
    path = np.random.choice(glob.glob(os.path.join(self.root_dir, name + '*.mp4')))
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

Any tip more?

**Comment by AliaksandrSiarohin** [comment]
Set id_sampling to False, or see how to name the files in https://github.com/AliaksandrSiarohin/first-order-model/blob/83d8d7be6a24bba8cf985d126c1eabab906d85bf/config/taichi-256.yaml#L7
In your case dicaprio#1.mp4

**Comment by Jefersonwulf** [comment]
> Set id_sampling to False, or see how to name the files in
> 
> https://github.com/AliaksandrSiarohin/first-order-model/blob/83d8d7be6a24bba8cf985d126c1eabab906d85bf/config/taichi-256.yaml#L7
> 
> 
> In your case dicaprio#1.mp4


Ahhhh I understand, so, in case you want to use the video frames in .png, should I create another folder inside the train? Or put as images there with these names image # 01.png ... image # 30.png ...
And so on for each picture right?

**Comment by AliaksandrSiarohin** [comment]
No name of the folder should match name of the video. So it should be dicaprio#1.mp4/1.png dicaprio#1.mp4/2.png and so on.

**Comment by Kagigz** [comment]
@AliaksandrSiarohin Hi, I have the same error as @Jessicall :

I had the same error as mentioned in issue #43 so I replaced mimread() by get_reader().

My code in read_video now looks like this:

```
video = get_reader(name)
video_np = np.array([frame for frame in video])
if video_np.shape[-1] == 4:
    video_np = video_np[..., :3]

video_array = img_as_float32(video_np)
```

Now when trying to run the script, during training there's an error 'CannotReadFrameError' (the same as posted above).

It occurs at line 50 in train.py, `for x in dataloader:``

Btw I'm using the Fashion dataset.

Any idea?

Thanks!

**Comment by SaharHusseini** [comment]
Hello,

I am encountering similar issue. I tried to use both id_sampling = False and True but neither of them worked for me. I attached a photo from my dataset folder, Yaml file and the error in the Colab. I appreciate it if you can provide me any help and advice
![FOM_error](https://user-images.githubusercontent.com/93087155/150651830-004e46cc-9f64-4779-ba2a-b547060ee8b6.png)
.
