### ISSUE TITLE
Reproducing the result

### ISSUE THREAD

**Issue by shiluooulihs** [AliaksandrSiarohin/first-order-model#72]
hi, great job!

I want to reproduce the result. But  the net seems collapsed after about 2400 iters every time.
I have tried vox-256.yaml and vox-adv-256.yaml.

I used one gpu: RTX 2080TI , and the batch size is 8.
Has anyone encountered this kind of problem。
![00000000-00004799-rec](https://user-images.githubusercontent.com/24603263/78344395-e55cd300-75ce-11ea-9a63-9112f2023758.png)

**Comment by AliaksandrSiarohin** [comment]
You should use pytorch==1.0.0 as explained in README.md
