### ISSUE TITLE
Out of cuda memory

### ISSUE THREAD

**Issue by vidstige** [AliaksandrSiarohin/first-order-model#73]
Is there a way to use less CUDA memory somehow? E.g. small block/batch sizes or otherwise. Otherwise I'll just buy a new graphics card. Thanks in advance.

Getting this from demo.py.
```RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 963.31 MiB total capacity; 497.39 MiB already allocated; 12.62 MiB free; 885.00 KiB cached)```

**Comment by AliaksandrSiarohin** [comment]
You have 1gb of memory? Are you using newest version? Yesterday I decrease memory requirements for demo slightly.

It is not clear at which point you run out of memory, so hard to tell if it can be improved. 

In worst case just use - - cpu option.

**Comment by vidstige** [comment]
Yeah, the `--cpu` option worked fine, but took ~ 30 mins. I didn't find a way to tweak memory usage. I had only 0.1GB GPU ram, but I bought a new card yesterday with 6GB and now it works perfectly. 👌

**Comment by ElmiraNa** [comment]
@vidstige 
Hi, I have a 6GB GPU, when I run demo.py It takes 3.8GB of memory and can not response 2 parallel requests for animate the photos. have you had any experience?
