### ISSUE TITLE
how to run on the cpu only

### ISSUE THREAD

**Issue by mrezarad** [AliaksandrSiarohin/first-order-model#74]
i couldn't find the cpu command it will run on gpu by defualt
my cpu is way more powerful than my gpu
could you help me plz?
thanks

**Comment by AliaksandrSiarohin** [comment]
python demo.py --cpu

**Comment by sqro2** [comment]
@AliaksandrSiarohin 
**unrecognized arguments: --cpu**   pls help

usage: demo.py [-h] --config CONFIG [--checkpoint CHECKPOINT]
               [--source_image SOURCE_IMAGE] [--driving_video DRIVING_VIDEO]
               [--result_video RESULT_VIDEO] [--relative] [--adapt_scale]
               [--find_best_frame] [--best_frame BEST_FRAME]
demo.py: error: unrecognized arguments: --cpu

**Comment by sqro2** [comment]
ok got it. had to update the demo.py file
