### ISSUE TITLE
imageio.core.format.CannotReadFrameError: Could not read frame 971: Frame is 0 byte, but expected 6220800

### ISSUE THREAD

**Issue by samurzele** [AliaksandrSiarohin/first-order-model#75]
As you might guess, I get the error in the title when trying to run the demo. I read that this is because it thinks there is one more frame in the video when in reality, there isn't. I don't know how to fix this tho, any help? The command I'm running is `python demo.py config/fashion-256.yaml --driving_video lol.mp4 --source_image lel.jpeg --checkpoint fashion.pth.tar --relative --adapt_scale`

**Comment by AliaksandrSiarohin** [comment]
Something wrong with your video try other video or change the code of this video. Also you can try to update imageio  and imageio-ffmpeg
