### ISSUE TITLE
result shows artifacts, maybe aliasing?

### ISSUE THREAD

**Issue by jc-zeitraum** [AliaksandrSiarohin/first-order-model#78]
When running the model through the colab notebook as well as locally, I get some patterns / artifacts.
Is there a way to remedy this, especially temporally?
![artifacts-gif](https://user-images.githubusercontent.com/61283134/78458661-6ab9b380-76b3-11ea-9003-8b2926c8d810.gif)

**Comment by AliaksandrSiarohin** [comment]
There is no easy way.
