### ISSUE TITLE
Ask for trained weight in Voxceleb

### ISSUE THREAD

**Issue by BaldrLector** [AliaksandrSiarohin/first-order-model#8]
Thanks for your great work.
I see the Voxceleb is used for training in your paper, but the weight is not shared for now.
So may I ask for uploading the trained weight file in Voxceleb, please.

Your reply will be appreciated, thank you.

**Comment by AliaksandrSiarohin** [comment]
We are still preparing for a full release. Contact me by email for details.

**Comment by wincle** [comment]
Also ask for it, it will be better to public it, thx!

**Comment by lorrp1** [comment]
First, great results and nice paper. 

can i ask you your email? i cant find.

ho visto uniTrento, parli italiano per caso?

**Comment by AliaksandrSiarohin** [comment]
"Also ask for it, it will be better to public it, thx!"
I know, but it not only depends on me. Though should be published soon.

"can i ask you your email? i cant find.
ho visto uniTrento, parli italiano per caso?"
aliaksandr.siarohin@unitn.it 
No, I don't speak Italian, sorry.

**Comment by AliaksandrSiarohin** [comment]
VoxCeleb and Nemo is released, thank you for waiting.

**Comment by tejaskhot** [comment]
@AliaksandrSiarohin Where are the VoxCeleb and Nemo pretrained models uploaded? They are not available at the checkpoint link in the README.

**Comment by AliaksandrSiarohin** [comment]
Sorry forgot to syncronise the cloud disk. Checkpoints should be there by now.
