### ISSUE TITLE
The training is going well?

### ISSUE THREAD

**Issue by Jefersonwulf** [AliaksandrSiarohin/first-order-model#80]
```
(base) PS C:\Users\jefer\Desktop\first-order-model-master> python run.py --config config/vox-adv-256_clone.yaml --device_ids 0
Use predefined train-test split.
Training...
  0%|                                                                                          | 0/150 [00:00<?, ?it/s]C:\Users\jefer\anaconda3\lib\site-packages\torch\nn\functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
C:\Users\jefer\anaconda3\lib\site-packages\torch\nn\functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
C:\Users\jefer\anaconda3\lib\site-packages\torch\nn\functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
 15%|███████████▌                                                                   | 22/150 [13:49<1:20:28, 37.73s/it]

```

And the log folder are creating this... I dont know if is right

![00000020-rec](https://user-images.githubusercontent.com/62947736/78462627-4ad1c200-76aa-11ea-849b-beb39194a1f7.png)

**Comment by AliaksandrSiarohin** [comment]
Never trained on a single video. Seems ok.

**Comment by white-cmd** [comment]
想问一下啊  在我执行命令时，它总是显示'CUDA_VISIBLE_DEVICES' 不是内部或外部命令，也不是可运行的程序
                      或批处理文件。  我该怎么做呢

**Comment by Lv-Jiahao** [comment]
I want to ask, when I execute an order, it always shows 'CUDA_VISIBLE_DEVICES' is not an internal or external command, nor a runnable program.
What should I do

**Comment by bajiua** [comment]
> ```
> (base) PS C:\Users\jefer\Desktop\first-order-model-master> python run.py --config config/vox-adv-256_clone.yaml --device_ids 0
> Use predefined train-test split.
> Training...
>   0%|                                                                                          | 0/150 [00:00<?, ?it/s]C:\Users\jefer\anaconda3\lib\site-packages\torch\nn\functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
>   warnings.warn("Default grid_sample and affine_grid behavior has changed "
> C:\Users\jefer\anaconda3\lib\site-packages\torch\nn\functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> C:\Users\jefer\anaconda3\lib\site-packages\torch\nn\functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
>   warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
>  15%|███████████▌                                                                   | 22/150 [13:49<1:20:28, 37.73s/it]
> ```
> 
> 日志文件夹正在创建这个...我不知道是否正确
> 
> ![00000020-rec](https://user-images.githubusercontent.com/62947736/78462627-4ad1c200-76aa-11ea-849b-beb39194a1f7.png)

Hi, how do you train with your own data set? I directly created a data set file, which contains test and train, and then changed data_root, but it cannot be trained, there is an error, I would like to ask what else needs to be modified?
