### ISSUE TITLE
Face Swap

### ISSUE THREAD

**Issue by BestBoyBerlin** [AliaksandrSiarohin/first-order-model#83]
Any plans on releasing the Face Swap, that is shown in the paper?

**Comment by c4tz** [comment]
Please use the search function next time:

https://github.com/AliaksandrSiarohin/first-order-model/issues/36
https://github.com/AliaksandrSiarohin/first-order-model/issues/15
https://github.com/AliaksandrSiarohin/first-order-model/issues/9 (Original question with answer from @AliaksandrSiarohin)

**Comment by BestBoyBerlin** [comment]
Just wanted to ask again, because the week is over.

**Comment by c4tz** [comment]
Oh okay, please leave a comment in the original issue then and close this one.

**Comment by BestBoyBerlin** [comment]
Ok thanks
