### ISSUE TITLE
Is there a tutorial for someone who isn't familiar with coding?

### ISSUE THREAD

**Issue by HeavysatOil** [AliaksandrSiarohin/first-order-model#85]
I love watching videos on all this stuff, came here from the 2minpaper yt, anyways ive never really tried coding so this stuff seems very confusing, is there a tutorial on how to start and use this deepfake stuff  if not dont worry, its still fun to just see what others can do.

**Comment by AliaksandrSiarohin** [comment]
If you are not familiar with coding, you can thought of it as a good opportunity to learn coding.  Here you have to go https://github.com/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb press open in colab and follow the simple steps.
