### ISSUE TITLE
Face swap?

### ISSUE THREAD

**Issue by lorrp1** [AliaksandrSiarohin/first-order-model#9]
Hello,

i have seen that on https://aliaksandrsiarohin.github.io/first-order-model-website/ you have published an example of face-swap, but i cant find the description of the method used in the paper or here. 

Thanks for reading.

**Comment by AliaksandrSiarohin** [comment]
Hi,
The face swap is some application of the proposed method. I can not publish it now. Contact me by email for the details.
Regards, AS

**Comment by lorrp1** [comment]
Ok, thanks

**Comment by ghost** [comment]
@AliaksandrSiarohin great work, any plans to release the face swap model in the future?

**Comment by AliaksandrSiarohin** [comment]
Thank you for your interest, face swap is not a model it is some additional application of the pretrained animation model, more details via email. I will realize the scripts for face swap, as soon as I get an approval of all authors.

**Comment by jjandnn** [comment]
非常棒，效率非常高。不愧是2.0的猴子。期待你进一步有突破！祝好！
Great, very efficient and worthy of the 2.0 monkey looking forward to your further breakthrough! I wish good

**Comment by spacewalkingninja** [comment]
hello, any updates?

**Comment by AliaksandrSiarohin** [comment]
I will try to release it by the end of the week.

**Comment by c4tz** [comment]
That's great to hear, thank you in advance!

**Comment by AliaksandrSiarohin** [comment]
https://github.com/AliaksandrSiarohin/motion-cosegmentation
```
python part_swap.py --source_image ... --target_video ... --checkpoint vox-first-order.pth.tar --config config/vox-256-10segments.yaml --supervised --first_order_motion_model
```
