### ISSUE TITLE
Training error 

### ISSUE THREAD

**Issue by sqro2** [AliaksandrSiarohin/first-order-model#96]
log - 

Use predefined train-test split.
Training...
  0%|                                                                                                                                                                                       
Traceback (most recent call last):
  File "run.py", line 77, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/home/machine-learning/first-order-model/train.py", line 87, in train
    'optimizer_kp_detector': optimizer_kp_detector}, inp=x, out=generated)
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by AliaksandrSiarohin** [comment]
Your dataset is emty, or less than one batch.
